### ISSUE TITLE
some shortcuts in code blocks don´t work in Mac

### ISSUE THREAD

**Issue by TCRobotics** [FPGAwars/icestudio#106]
Mac 10.11.4
ctrl+c, cmd+c, ctrl+v, cmd+v, ctrl+x, cmd+x, ctrl+z

working: cmd+z

**Comment by Jesus89** [comment]
Solved: release 0.2.3

This is an nwjs issue: https://github.com/nwjs/nw.js/issues/1955.

Only cmd-c, cmd-v, cmd-x must work in Mac. (ctrl-c, ctrl-v, ctrl-x are not used for copy, past and cut).
