### ISSUE TITLE
Include a base directory "icestudio" in the zip files

### ISSUE THREAD

**Issue by javacasm** [FPGAwars/icestudio#107]
When the release zip files is unzip all the files go the current directory.
In my opinion, it would be better include a base "icestudio" directory.

**Comment by Jesus89** [comment]
Hi,

I think in Windows 10 you can select the option (Create a directory and unpack) to avoid this problem. Also in Linux the directory is automatic created if needed.

However, I think it is a good proposal in order to create a common multiplatform behavior.
