### ISSUE TITLE
Archivo patch-iCE40-HX8K.py sin salida D16

### ISSUE THREAD

**Issue by tonicobi** [FPGAwars/icestudio#111]
En el archivo patch-iCE40-HX8K.py faltaba la salida **D16**.
Lo adjunto con la corrección.
[patch-iCE40-HX8K.zip](https://github.com/FPGAwars/icestudio/files/629176/patch-iCE40-HX8K.zip)

**Comment by Jesus89** [comment]
Efectivamente, voy a actualizar el script. Gracias!
PD: el fichero pinout.json se genera a partir del PCF. En este caso parece que se ha duplicado el pin B16 y no incluido el D16: https://github.com/FPGAwars/icestudio/blob/develop/app/resources/boards/iCE40-HX8K/pinout.pcf#L171.
