### ISSUE TITLE
Drivers en Windows 8.1 64 bits

### ISSUE THREAD

**Issue by tonicobi** [FPGAwars/icestudio#112]
Estoy trabajando con la placa **ICE40-HX8K** en Windows 8.1 con 64 bits, y no consigo que **Icestudio** detecte la placa. Instalé los drivers **libusbk**, como adjunto en una captura, pero no hay forma. Lo he intentado en varios ordenadores con el mismo sistema operativo.

Sin embargo en Ubuntu funciona todo a la primera.

Por otro lado estaría genial que Icestudio aceptara **etiquetas** para los cables, de forma parecida a como se hace en Altium Designer a la hora de hacer esquemas. Simplificaría mucho todo.

Muchas gracias.

![ftusb](https://cloud.githubusercontent.com/assets/18178389/20866973/552e3bdc-ba3a-11e6-8366-4f9cdf99b810.jpg)

**Comment by Jesus89** [comment]
Buenas,

Recuerda desconectar y conectar la placa cuando modifiques los drivers. Para una análisis más detallado puedes seguir este tutorial https://github.com/FPGAwars/libftdi-cross-builder/wiki#driver-installation. 

Te recomiendo escribir a la lista: https://groups.google.com/forum/m/#!forum/fpga-wars-explorando-el-lado-libre donde te podrán ayudar también los demás miembros de la comunidad y usuarios de la placa de 8K.

Gracias por la propuesta de las etiquetas, la apuntamos para futuras versiones.

**Comment by Jesus89** [comment]
Info:

Continúa en el hilo: https://groups.google.com/forum/#!topic/fpga-wars-explorando-el-lado-libre/PbwgXNE4kcU
