### ISSUE TITLE
Can't execute icestudio properlly after update.

### ISSUE THREAD

**Issue by C47D** [FPGAwars/icestudio#127]
Hi, thanks for the improvements :)
Just updated icestudio from git and when trying to execute it i got the following screen shoot.
![icestudio](https://cloud.githubusercontent.com/assets/11037705/22137056/58de0d38-de9e-11e6-9e80-c215c0915236.png)

Just to ask if somebody have the same results.

Thanks in advance.

**Comment by Jesus89** [comment]
Hi Carlos,

Please, can you attach your current commit? Also you can launch the developer window: app/package.json -> window.toolbar = true. Launch the app again, and capture the console window.

![icestudio-debug](https://cloud.githubusercontent.com/assets/2227572/22138615/e0f805b4-dee1-11e6-99e6-c62cbf152c7a.png)

**Comment by C47D** [comment]
Hi Jesús,
Current commit:
![commit](https://cloud.githubusercontent.com/assets/11037705/22139826/4a99d2f6-deae-11e6-9353-f4dae97901d3.png)

After setting window.toolbar = true and try to run the application i got the same as the first attachment and here's the console output:
![consolewindow](https://cloud.githubusercontent.com/assets/11037705/22139941/0b7636e0-deaf-11e6-8114-56e382695f29.png)

Thanks for the quick reply, hope the attachments are correct

**Comment by C47D** [comment]
Hi,
After changing back toolbar to false i did:
$ npm install
$ npm start

And seems to be working great as always. Here a couple of screen shoots:
![ice1](https://cloud.githubusercontent.com/assets/11037705/22140148/2aed2b36-deb0-11e6-8557-19e1383852b6.png)

![ice2](https://cloud.githubusercontent.com/assets/11037705/22140151/31738a72-deb0-11e6-9b51-875850446376.png)

Thanks again for the continuous improvement :).

I think the issue is solved.

**Comment by Jesus89** [comment]
Great. Thanks for testing!
