### ISSUE TITLE
Possible ignored commit

### ISSUE THREAD

**Issue by 1138-4EB** [FPGAwars/icestudio#146]
These notifications are shown in my timeline:

> - 3 hours ago Jesus89 pushed to develop at FPGAwars/icestudio
>   - @Jesus89 da1fb23 Move languages menu to a new file 
>   - @Jesus89 38df3c2 Update Readme 
>- 3 hours ago Jesus89 pushed to develop at FPGAwars/icestudio
>   - @Jesus89 f5ac920 Update Readme 
>- 6 hours ago Obijuan pushed to develop at FPGAwars/icestudio
>   - @Obijuan 86cf704 Update README.md 

@Objuan's 86cf704 is built on top of 81741b5, and @Jesus89's f5ac920 is built on top of 86cf704. However, 38df3c2 and da1fb23 are built on top of 81741b5. As a result, @Obijuan's changes are not shown in the current `develop` branch.

f5ac920 and 38df3c2 do the same changes, but the first is orphan now, and the latter might have been added in a local copy prior to fetching @Obijuan's changes.

**Comment by Jesus89** [comment]
Hi, that commit was not correct. It is not included in the git tree.
The current develop branch is correct. You can update using `git fetch --all` and `git reset --hard upstream/master` (being upstream the FPGAwars remote).
