### ISSUE TITLE
Fail to install today's develop branch in MAC (MacOS sierra 10.12.3)

### ISSUE THREAD

**Issue by andrespmt** [FPGAwars/icestudio#152]
I did the clone, nom install, and got the errors that are in the attached log.
Not sure if i am missing some important libraries... yesterday i was able to run Icestudio by using the DMG package that you have.
I was trying to use the latest to add my SVG to my component

**Comment by andrespmt** [comment]
[npm-debug.log.txt](https://github.com/FPGAwars/icestudio/files/866906/npm-debug.log.txt)

Please remove .txt extension and leave is with .log. I did that to be able to upload the file

**Comment by Jesus89** [comment]
Hi,

Try to update your nodejs version: https://nodejs.org/es/download. You can check it with:
```bash
$ node -v
$ npm -v
```

Then, execute ``npm install`` again.

**Comment by andrespmt** [comment]
I am not sure what did happen, but I ended up installing NODE, NPM, GRUNT and now back to normal and is working. In Windows it did work from the beginning.
Thx. Closing this ticket.

**Comment by Jesus89** [comment]
Great! :grinning:
