### ISSUE TITLE
python-2.7.13.amd64.msi inside icestudio-0.3.0-rc-win32.exe build

### ISSUE THREAD

**Issue by mtve** [FPGAwars/icestudio#153]
there is python-2.7.13.**amd64**.msi inside icestudio-0.3.0-rc-win32.exe build

apparently for win32 it should be `https://www.python.org/ftp/python/2.7.13/python-2.7.13.msi` in `gruntfile.js` and in `scripts/windows_installer.nsi`

sorry, i'm not brave enough for a patch

**Comment by Jesus89** [comment]
Good point. Thanks!
Here is the patch: https://github.com/FPGAwars/icestudio/commit/e80c2f5f7c8ca69fe2f8ac519f7095fa501f7634
