### ISSUE TITLE
En la barra de acciones superior de MacOS sale 'nwjs'

### ISSUE THREAD

**Issue by andrespmt** [FPGAwars/icestudio#155]
no se si es por el framework de Node? Pero se podria poner IceStudio?

**Comment by Jesus89** [comment]
Buenas Andrés,
Cuando ejecutas Icestudio App desde el ZIP o DMG no te aparece 'nwjs' sino 'icestudio'.
En el modo desarrollador (npm start) sí te aparece 'nwjs' porque es el binario principal para lanzar la app. Como sólo aparece en develop no supondría ningún problema.
De todas formas confirma que es así también en tu ordenador.
Un saludo.

**Comment by andrespmt** [comment]
Todo claro ahora. 
Gracias
