### ISSUE TITLE
Control+U shortcut doesn't trigger the upload action

### ISSUE THREAD

**Issue by vrruiz** [FPGAwars/icestudio#157]
Test case.
- Open IceStudio and connect the Icezum Alhambra.
- Open example "Four bits fixed binary value".
- Click on the code block.
- Press Control+U.

Expected result.
- Program is compiled and uploaded.

Actual result.
- Program is not compiled nor uploaded.

The shortcut is used by the editor to convert selected text to uppercase.

Tested on Ubuntu with Icestudio version 0.3.0-rc.

**Comment by C47D** [comment]
I have the same issue, clicking outside the code editor and then pressing Ctrl + U work as expected.

**Comment by Jesus89** [comment]
Hi, this was fixed in dd455c148f62c4b5c13a2728a2a0d1d69b1e1949. Please try the develop branch to ensure that it works properly.

**Comment by C47D** [comment]
Hi, It works properly now, thanks for the quick fix.
