### ISSUE TITLE
Enhacement/Suggested opcion: Enable/DIsable multiple connections

### ISSUE THREAD

**Issue by jcarolinares** [FPGAwars/icestudio#158]
Hi!

I'm triying to make this simple circuit (a part of a very low level register)

![suggestion_multiple_connections](https://cloud.githubusercontent.com/assets/7687624/25448619/5c70f2a0-2ab9-11e7-8d62-5ccd40da2e42.png)

But Icestudio says me that "multiple inputs connections are not allowed" 

I know that is delicate and the fpga could be damaged but It could be awesome if you put an advanced option to Enable or Disable the multiple inputs connections to make this kind of basic exercises.

Greetings

**Comment by Jesus89** [comment]
Hi!

Icestudio allows this connections but always from output to input: you can extract multiple connections from an output port.

The error "Invalid multiple input connections" appears when you try to connect a wire to an already connected input port, but this is not the case.

I attach the [or-test.txt](https://github.com/FPGAwars/icestudio/files/959518/or-test.txt) (->.ice)
![or-test](https://cloud.githubusercontent.com/assets/2227572/25452525/2c95fd52-2ac6-11e7-8394-ab821cec0adb.png)

Btw, I recommend to follow the design rules to avoid possible strange behaviors in your designs.

Regards.
