### ISSUE TITLE
Update NW.js

### ISSUE THREAD

**Issue by Jesus89** [FPGAwars/icestudio#160]
http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13

0.12.3 -> 0.28.0

**Comment by Jesus89** [comment]
Since version 0.13.0, generated icestudio file (in Linux) is not executable anymore by double-click...

**Comment by Obijuan** [comment]
Nw.js has been updated to 0.35 in icestudio 0.5.1-nigthly, so I think this issue can be closed
