### ISSUE TITLE
Change the project status to not-saved when their information is modifyied

### ISSUE THREAD

**Issue by Obijuan** [FPGAwars/icestudio#162]
When a modificatión is done in a project, its state change to non-save and the symbol * appears on the top-left corner.  When the project information is changed (Edit/preference/project information), like the description or the icon, the state is not updated to non-saved. Currently you have to remember to save the project after changing the information. It is easy to do, but sometimes you can forget it and the data is lost

**Comment by Jesus89** [comment]
Done https://github.com/FPGAwars/icestudio/commit/2a96eab366589b4fea5f1fa14b79b1559162337f.
