### ISSUE TITLE
Support for the BlackIce Mystorm?

### ISSUE THREAD

**Issue by andreacampanella** [FPGAwars/icestudio#184]
Would be great to have support for the Mystorm : 
https://mystorm.uk/

the schematics are here : 
https://gitlab.com/Folknology/mystorm/blob/BlackIce/BlackIce-schematic.pdf

**Comment by Jesus89** [comment]
PCF: https://github.com/mystorm-org/BlackIce-II/blob/master/examples/common/blackice-ii.pcf
