### ISSUE TITLE
[Feature] Blocks replacement

### ISSUE THREAD

**Issue by Obijuan** [FPGAwars/icestudio#191]
Currently, if you want to change one block for another (for example an updated block), you have to delete that block and insert the new one. The problem is that you lost all the connections. This is a little bit painful when your design is complex.

In addition, the replacement feature makes the exploration process of newbies much easier. Here are some examples, starting from the simplest one

* Changing the state of a led:

This is the circuit for turning a led on:

![ledon-01](https://user-images.githubusercontent.com/1286062/34597816-7c357226-f1e9-11e7-92bd-2cf6b043f6cc.png)

With the replacement feature, you pick a new block, for example a bit 0:

![ledon-03](https://user-images.githubusercontent.com/1286062/34597976-5fbf1682-f1ea-11e7-911c-37c06e43433a.png)

put it over the block you want to change

![ledon-04](https://user-images.githubusercontent.com/1286062/34597995-79ffadf4-f1ea-11e7-8bf2-a8f32adaacc3.png)

click the mouse button and the block is replaced

![ledon-05](https://user-images.githubusercontent.com/1286062/34598035-b69a6dd0-f1ea-11e7-9ada-839c6e75b5b4.png)

If you replace a block by error, you can use ctr-z (undo) to move back to the previous state

Now imagine you want to  make the led blinks. You just replace the bit by a heart. Pick the heart and put it over the block and click the button

![ledon-06](https://user-images.githubusercontent.com/1286062/34598235-c08ae1d4-f1eb-11e7-9d60-519ffd667a93.png)

![ledon-07](https://user-images.githubusercontent.com/1286062/34598252-d78c480a-f1eb-11e7-9f27-4e0be0ee9d66.png)

I really think that this feature will make a difference in the educational project. I can image an icestudio sheet, with a simple circuit (like the hello world before) and different blocks on the left that change the behaviour on the led. The student just drag the blocks to test what they do with the led

![ledon-08](https://user-images.githubusercontent.com/1286062/34598423-e71937a0-f1ec-11e7-934b-46d3b54dcd38.png)

There are many details that should be cover. Let's use this issue to document them

**Comment by Obijuan** [comment]
It would be great if the replacement works also with code blocks:

![ledon-09](https://user-images.githubusercontent.com/1286062/34598521-84886ef2-f1ed-11e7-8231-84a76a3ae54b.png)

![ledon-11](https://user-images.githubusercontent.com/1286062/34598565-d95f54c2-f1ed-11e7-9e49-c87e6e3523ee.png)

It brings the question... if the blocks have different names for their outputs, how should the replacement proceed? This is something that we should solve by using it. We will discover the rules as we test it

One rule might be:  
1. If the two block have the same number of outputs, regardless of their names, the replacement operation will be done.   

This rule will cover the above case

**Comment by Obijuan** [comment]
One important thing is that the wiring should remain the same after the replacement. I know it should be hard to implement. Let's say we have this circuit

![ledon-13](https://user-images.githubusercontent.com/1286062/34598868-7efe4400-f1ef-11e7-9bf4-b27eb55a6935.png)

And we want to replace the 1 by the heart. After the replacement has been done, the wiring should stay the same:

![ledon-14](https://user-images.githubusercontent.com/1286062/34598892-9af0207a-f1ef-11e7-90a1-d75efe9cccb6.png)

**Comment by Jesus89** [comment]
Hi!

I have created a PR for this: https://github.com/FPGAwars/icestudio/pull/198.

Now you can replace Generic, Code and Info blocks. When the block is replaced, the wires are replaced for each side (left, right and top). First: it tries to match the same name & size connections. Second: if there are ports with the same name, they are replaced by position.

The algorithms has also two steps: create a portsMap between the lowerBlock and the upperBlock, and try to replace the connected wires using this portsMap.

It also preserves the wire's vertices and Undo/Redo works for move&replace and create&replace blocks.

The only thing missing is the match between ports with different name. I need to figure out how to define this behavior to be consistent with the current algorithm.

**Comment by Jesus89** [comment]
I have added the following rule. This rule is applied after the first names&size match:
> If there is no match replace the connections if the port's size matches ignoring the port's name.

This is an example:

![drag replace - 3](https://user-images.githubusercontent.com/2227572/35192111-95e42ccc-fe8b-11e7-9b88-a30734bf1f4c.gif)

**Comment by Obijuan** [comment]
That's awesome! Thanks!  :-)

**Comment by Obijuan** [comment]
I think that this issue can be closed.  We all can test it and create a new issue when a bug is found
