### ISSUE TITLE
Zadig is not launched

### ISSUE THREAD

**Issue by Jesus89** [FPGAwars/icestudio#204]
In the version 0.3.2-beta, Zadig is not launched in "Drivers > Enable". Also the message `Error: ENOENT: no such file or directory ...profile.json` still appears. Let's fix that.

More information in this [video](https://www.youtube.com/watch?v=Ux1yy5b0fB8)

**Comment by Obijuan** [comment]
Eladio just confirmed this bug. He tested the installation in a W7-64 machine and confirmed that zadig is not launched

**Comment by Jesus89** [comment]
Closed by: 4ab255f6089709630029e2adeb50882bd66fd9be
