### ISSUE TITLE
Add updated `setuptools` and `wheel` packages

### ISSUE THREAD

**Issue by Jesus89** [FPGAwars/icestudio#205]
These packages must be updated to install SCons. So:

- [x] Add offline packages to the app bundle
- [x] Install these packages before `apio` in the icestudio virtualenv

**Comment by ColRod** [comment]
Tras ejecutar en consola:
pip install -U setuptools
pip install -U wheel
y despues de que la maquina actualizase, sigo con el mismo problema que me impide instalar Toolchain en 0.3.2-beta
![captura de pantalla 2018-02-19 a las 8 42 21](https://user-images.githubusercontent.com/11178599/36366990-d92c7b98-1550-11e8-9603-0d3431597710.png)

**Comment by Jesus89** [comment]
Hola @ColRod.

Para actualizar esos paquetes en icestudio tienes que activar el virtualenv (`~/.icestudio/venv`) e instalar ahí los paquetes. En Linux sería:

```
source ~/.icestudio/venv/bin/activate
pip install -U setuptools
pip install -U wheel
```

De todas formas la solución que voy a implementar es tener los paquetes actualizados descargados en local e instalarlos antes que apio.

**Comment by Jesus89** [comment]
[Apio v0.4.0b1](https://github.com/FPGAwars/apio/releases/tag/v0.4.0b1) cambia el sistema de instalación de scons por lo que ya no requiere que estos paquetes estén instalados.

Sin embargo, dejo las funciones de pre-instalación de paquetes por si en el futuro fuera necesario instalar algún paquete externo de Python.
