### ISSUE TITLE
Fully migration to python3

### ISSUE THREAD

**Issue by Obijuan** [FPGAwars/icestudio#207]
Fully installation of icestudio with python3

- [x]  Fully migration of Apio to python3 ([Issue](https://github.com/FPGAwars/apio/issues/145))
- [ ] Add python3 to the installation (virtual env, windows installer, etc...)

**Comment by Jesus89** [comment]
Related to: https://github.com/FPGAwars/icestudio/issues/187

**Comment by Obijuan** [comment]
Done!
