### ISSUE TITLE
Improving the drivers installation in windows

### ISSUE THREAD

**Issue by Obijuan** [FPGAwars/icestudio#208]
Eladio commented how the we can improve the installation of the drivers in Windows, so that some problemas can be minimized

This is the information that is displayed in Windows when the install driver menu is clicked:

![img-20180217-wa0006](https://user-images.githubusercontent.com/1286062/36353129-a1d13546-14c2-11e8-932c-030bca6de253.jpg)

The first point should be modifyed to say something like:

1. Plug the FPGA board to the USB and wait until windows finished the default driver installation

( Once is finished, you can open the installation windows and see something like:)

![img-20180217-wa0007](https://user-images.githubusercontent.com/1286062/36353166-f243746c-14c2-11e8-9267-c929aead8740.jpg)

2.  When the OK button is clicked, the zading application will be launched, for replacing the default driver for another that works ok with icestudio

3. In zadig, replace the (Interface 0) driver of the board by libusbK

4. Unplug and reconnect the board

Eladio said that in some cases it can happens that zadig is launched when the windows default driver has not been fully installed, causing problems

I think that it is something that can also be included in the doc

**Comment by Jesus89** [comment]
Closed by db3aef29d256dbac7b11df9bc5aa7162264006e3
