### ISSUE TITLE
Install Toolchain doesnt work

### ISSUE THREAD

**Issue by pmezydlo** [FPGAwars/icestudio#213]
After running "Tools -> Toolchain -> Install"  I see error message "Toolchain not installed". How to check what is wrong during install?

**Comment by Jesus89** [comment]
Hi @pmezydlo.

Have you tested the development version? I have added today a patch for that issue. Please update your `develop` branch and try again.

Regards

**Comment by pmezydlo** [comment]
Hi

Yeah, It works well, thanks for help.

Regards
Patryk
