### ISSUE TITLE
unable to install the toolchain for TinyFPGA B2 on macOS 10.13.4 and icestudio 0.3.2

### ISSUE THREAD

**Issue by dennyalbert** [FPGAwars/icestudio#220]
Install process stop working with „Create virtualenv…“.

![icestudio_0 3 2_macos_tinyfpgab2_toolchain](https://user-images.githubusercontent.com/37122033/39096119-ea95753e-464b-11e8-8916-f656353daa3e.png)

**Comment by Jesus89** [comment]
Hi, please try [0.3.2-beta](https://github.com/FPGAwars/icestudio/releases/tag/0.3.2-beta) version.

As soon as I get a Mac I'll fix the issue.

Thanks!

**Comment by blkhawk** [comment]
I have the same problem - There are a bunch of "Operation not Permitted" errors on some .so files in ~/.icestudio/..  The files exist and seem to have the right permissions.

**Comment by Jesus89** [comment]
Maybe related to this commit: https://github.com/FPGAwars/icestudio/commit/c0e66a2eec47a1ac3e94346087670a0522d9b14f

We have tested that 0.3.0 version works. The one using `tar.gz` for the virtualenv instead of `zip`.

**Comment by Jesus89** [comment]
Hi @blkhawk.

I finally get a High Sierra Mac and fix the issue. I have replaced the installers here: https://github.com/FPGAwars/icestudio/releases/tag/0.3.2.

Please, check that this is also fixed in your computer.

Regards.
