### ISSUE TITLE
Add option to allow user to reload currently selected collection from disk

### ISSUE THREAD

**Issue by adumont** [FPGAwars/icestudio#225]
If user adds/removes blocks at the filesystem level to a collection (while working on enhancing a collection for example), in .icestudio/collections/... the collection won't refresh /reload to show the changes.

It would be great to have an option in the menu to reload the collection from disk.

**Comment by Jesus89** [comment]
Done! 8d3ffbed5f1783073d2849ce528c34c95e2da7c5

Just go to `Tools > Collections > Reload`
