### ISSUE TITLE
allow selection of multiple collections

### ISSUE THREAD

**Issue by javierpuche** [FPGAwars/icestudio#239]
It would be great to be able to have tools from different collections without having to switch from one to another. Just an idea in case it is not too difficult to implement and it does not break other things or concepts.
Thanks a lot anyhow.

**Comment by cavearr** [comment]
Hi! in the last WIP,  we introduce a new plugin to manage collections, you could use all of your collections together.

If you would to see in action you can view here:

https://youtu.be/TWnnmXevXKo?t=392

If you want to try the last wip you can download from:

https://downloads.icestudio.io

Thanks for your feedback!
