### ISSUE TITLE
how to declare inout port with Basic Code block

### ISSUE THREAD

**Issue by itviewer** [FPGAwars/icestudio#249]
there are only input and output  box , how can I insert `inout` type port?
thanks

**Comment by Obijuan** [comment]
You have to use the in-out blocks.

I've written some documentation here (It is in spanish, but you can see the circuit and figures):

https://github.com/Obijuan/Cuadernos-tecnicos-FPGAs-libres/wiki/CT.3:-Pines-de-Entrada-Salida

Install the Jedi Collection from here:

https://github.com/FPGAwars/Collection-Jedi

You can have a look at the examples in Files/Examples/Pines-ES
