### ISSUE TITLE
mensaje al actualizar el toolchain

### ISSUE THREAD

**Issue by ionhsFP** [FPGAwars/icestudio#256]
He instalado el toolchain (Windows 10 x64), pero al no conseguir cargar a la placa he vuelto a reinstalar el toolchain y me ha salido el error o advertencia de la imagen. Tras lo cual al pulsarla desaparece la advertencia en rojo pero la evolución queda bloqueada en 30%

![sin titulo](https://user-images.githubusercontent.com/11555122/44299621-389ae880-a2fa-11e8-95b0-7ea7811fb76e.png)

**Comment by Jesus89** [comment]
Hola. El mensaje indica que no tienes `git` instalado y no puede instalar apio desde GitHub. Sin embargo no instales git. Esto es porque está activado un flag de debug para forzar el uso de git.

Te comento los pasos a seguir:

1. Ejecuta `Herramientas > Toolchain > Reset default`. Esto te debería funcionar ya que instala la herramientas almacenadas en el instalador y no necesita conexión a internet.
2. Voy a actualizar el paquete de release sin el flag de apio. Cuando esté subido te lo comento en la issue, te lo descargas y pruebas esta misma opción de `Herramientas > Toolchain > Actualizar`.

La parte de la detección de la placa puede que tenga que ver con los drivers. Ejecuta `Herramientas > Drivers > Habilitar`.

**Comment by Jesus89** [comment]
He actualizado el paquete. Prueba a descargar win64.exe de nuevo y probar el punto 2.

**Comment by ionhsFP** [comment]
Hola Jesus89 el tema del Toolchain parece correcto. Con el driver me está dando guerra, sigo los pasos, Herramientas/Driver/Habilitar sale un mensaje sobre le virtual serial driver que todo está correcto (adjunto foto). Pero al cargar un ejemplo sale la barra cargando y a los pocos segundos sin desaparece vacía sin parecer que haya cargado nada. He hecho varios intentos, cargar drivers, toolchain, apagar y encender el icestudio y sale la barra vacía y debajo un cuadrado rojo sin texto (subo captura).
Reiniciaré el pc a ver si es eso, pero pocas pruebas más se me ocurren.
![sin titulo](https://user-images.githubusercontent.com/11555122/44302533-18375200-a32b-11e8-80e7-6967e16ce1e2.png)
![sin titulo1](https://user-images.githubusercontent.com/11555122/44302536-18375200-a32b-11e8-820c-06255f2188d5.png)

**Comment by Jesus89** [comment]
Buenas @ionhsFP,

He solucionado un bug en apio relacionado con este tema. Estará disponible en la próxima versión estable de Icestudio.

Gracias por el feedback.
