### ISSUE TITLE
Las colecciones no se instalan en Mac OSX

### ISSUE THREAD

**Issue by ghost** [FPGAwars/icestudio#265]
Saludos.
Siguiendo los tutoriales llego al que instalamos las colecciones en IceStudio; sigo las instrucciones al pie de la letra pero no se me instalan.

Maquina: iMac
SO: macOS High Sierra
IceStudio Version 0.3.2

Pantallazos del proceso:
![p01](https://user-images.githubusercontent.com/34575034/44712740-c53f6680-aab1-11e8-8d83-d17d4b841088.png)
![p02](https://user-images.githubusercontent.com/34575034/44712751-cd97a180-aab1-11e8-84e2-70cf4334b079.png)
![p03](https://user-images.githubusercontent.com/34575034/44712757-d12b2880-aab1-11e8-85a6-cde38fe36e18.png)

Lamento no poder proporcionar mas informacion, pero no me da ninguna; ni fallos, ni iformes de error ni nada. Sencillamente no ocurre nada.

Alguna idea?

**Comment by Jesus89** [comment]
Hola,

Puedes probar con esta versión? https://github.com/FPGAwars/icestudio/releases/tag/v0.3.3-rc.

**Comment by charliva** [comment]
I confirm this bug is solved and the latest version works correctly in macosx Mojave.
