### ISSUE TITLE
Colecciones

### ISSUE THREAD

**Issue by xv5004** [FPGAwars/icestudio#268]
Se pueden instalar las colecciones manualmente em Mac OSX?
como y donde?

**Comment by Jesus89** [comment]
Buenas,

Como comento en este issue (https://github.com/FPGAwars/icestudio/issues/265) prueba a ver si te funcionan correctamente las colecciones con la versión 0.3.3-rc.

De todas formas puedes instalar manualmente las colecciones internas descomprimiendo directamente el zip en:

```
~/.icestudio/collections
```

También, (en la versión 0.3.3-rc) puedes configurar un directorio para cargar colecciones externas. (Edit > Preferences > External collection).

Un saludo.

**Comment by xv5004** [comment]
Ahora si, todo perfecto.

Si he tardado en responder es porque todavia no me habia llegado la Alhambra II… YA LA TENGO :D


El 3 set 2018, a les 5:15, Jesús Arroyo Torrens <notifications@github.com<mailto:notifications@github.com>> va escriure:


Closed #268<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FFPGAwars%2Ficestudio%2Fissues%2F268&data=02%7C01%7C%7C33cd9b5e23974d2b0f8208d6114b7477%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636715413098726320&sdata=DQHVcgL8R64hWdRbsG3UZnvwCSeH%2Bae7q%2Frw%2BSIsQDI%3D&reserved=0>.
