### ISSUE TITLE
[BUG] Icestudio is closed and open again when a command from the Tools menu is executed

### ISSUE THREAD

**Issue by Obijuan** [FPGAwars/icestudio#27]
I am opening an example (or create a new one from scratch). Then when I click on any of the entries of the tool menu, the icestudio is closed and opened again, losing the current circuit.

If I click on upload, The bitstream is generated and upload into the board, but then the icestudio is reset.

I have tested from the develop branch

**Comment by Jesus89** [comment]
Fixed in: 05674f43c945a7b182577a4520d1719d1f2b2a29
