### ISSUE TITLE
Error enable drivers in Mojave

### ISSUE THREAD

**Issue by CyberMODE** [FPGAwars/icestudio#280]
Since I install Mojave i can´t enable drivers in Mac Pro 5.1

![captura_drivers](https://user-images.githubusercontent.com/35894605/46692651-278a9b80-cc08-11e8-9e6f-1c7056e282ab.png)

**Comment by Obijuan** [comment]
Could you test it again using the latest icestudio wip version? You can download it from here:
https://downloads.icestudio.io/

**Comment by cavearr** [comment]
I'm closing the issue for not having reply and not be a global problem detected in other users.

If you need help about it , reopen it please!
