### ISSUE TITLE
Error al cargar codigo

### ISSUE THREAD

**Issue by xupatintes** [FPGAwars/icestudio#289]
Buenos dias.
He descargado en varios ordenadores el Icestudio para trabajar con la placa Alambra II , en todos me da el mismo error, no se que es lo que estoy haciendo mal.
Me sale el error:
ftdi_usb_get_strings failed: - 4 ( libusb_open() failed)
Gracias.

**Comment by charliva** [comment]
Aquí tienes un hilo que comenta este problema:

https://groups.google.com/forum/#!topic/fpga-wars-explorando-el-lado-libre/N0GxqQz0XFw

**Comment by xupatintes** [comment]
Muchas gracias, lo probare.
