### ISSUE TITLE
Python 2.7 is not installed automatically, contrary to docs

### ISSUE THREAD

**Issue by gojimmypi** [FPGAwars/icestudio#292]
The docs [here](https://icestudio.readthedocs.io/en/latest/source/installation.html#windows) state that Python will be installed automatically.

![image](https://user-images.githubusercontent.com/13059545/50385693-af495780-06d9-11e9-8ac5-f7a294a668b5.png)

Upon launching, click on the "click here"...
![image](https://user-images.githubusercontent.com/13059545/50385674-6ee9d980-06d9-11e9-951e-9e33cca0ea45.png)

Then on the "Python 2.7 not installed" message...
![image](https://user-images.githubusercontent.com/13059545/50385699-cd16bc80-06d9-11e9-938a-b8f67e9740c2.png)
nothing happens.

Note that I already have Python 3.6 installed:
![image](https://user-images.githubusercontent.com/13059545/50385711-1ebf4700-06da-11e9-844b-08538c6d924d.png)

**Comment by ximocat** [comment]
https://groups.google.com/d/msg/fpga-wars-explorando-el-lado-libre/wDVYpd6qNCo/VeCjulUtDQAJ

**Comment by Obijuan** [comment]
Fixed In icestudio 0.5.1-nigthly. It has been migrated to python 3.7
You can download from here: https://icestudio.io/#lk-download
