### ISSUE TITLE
Windows Installer wants Python 2.7.13 despite 2.7.14 already installed

### ISSUE THREAD

**Issue by gojimmypi** [FPGAwars/icestudio#293]
As noted in issue #292 Python was not installed automatically from the [zip file](https://github.com/FPGAwars/icestudio/releases/download/v0.4.0-dev/icestudio-0.4.0-dev-win64.zip) version of IceStudio, nor does it detect if Python manually installed. I have Python 2.7.14 installed, and this time I am running the [downloaded full exe](https://github.com/FPGAwars/icestudio/releases/download/v0.4.0-dev/icestudio-0.4.0-dev-win64.exe) to install IceStudio.

![image](https://user-images.githubusercontent.com/13059545/50386053-f89ca580-06df-11e9-973c-f9918231882b.png)

I was prompted to install Python 2.7.13:
![image](https://user-images.githubusercontent.com/13059545/50386056-04886780-06e0-11e9-9b3d-5e027568d60e.png)

Clicking "yes" IceStudio install seems to have completed successfully, although Python 2.7.14 is still installed (not replaced with this installer)
![image](https://user-images.githubusercontent.com/13059545/50386101-e96a2780-06e0-11e9-8fde-d2508f323c06.png)

I receive the same errors about the toolchain not installed, however when installing via the exe ... seems to have successfully installed the toolchain upon clicking the box. 

I'm using Windows 10 version 1809

**Comment by ximocat** [comment]
https://groups.google.com/d/msg/fpga-wars-explorando-el-lado-libre/wDVYpd6qNCo/VeCjulUtDQAJ

**Comment by Obijuan** [comment]
Please, try again with Icestudio 0.5.1-nigthly
