### ISSUE TITLE
Blank error messages in code block

### ISSUE THREAD

**Issue by charliva** [FPGAwars/icestudio#305]
If you have some kind of syntax errors inside a code block, sometimes error message is blank and you don't know where is the problem.

At this moment, i 'm using output command viewer and open the temporaly main.v generated file to look for error.

I'm attaching icestudio with test design open (attach it too) with no command at the end of line.

An screenshot with blank error.

![test_blank_error](https://user-images.githubusercontent.com/6904865/52472251-1be9ba00-2b93-11e9-92f6-c41471860065.jpg)

[tests_errores.zip](https://github.com/FPGAwars/icestudio/files/2844625/tests_errores.zip)

**Comment by charliva** [comment]
I'm fixed it and I do a pull request.

An screenshot with problem solved:

![test_blank_error_solved](https://user-images.githubusercontent.com/6904865/52472778-6ae41f00-2b94-11e9-9395-626dd329d2cc.jpg)

**Comment by Obijuan** [comment]
Checked! It works! :-)  Thanks!

**Comment by Jesus89** [comment]
Thanks @charliva!

**Comment by TimRudy** [comment]
Can you check this on 0.5.1-nightly? iverilog or yosys errors are not piped to the existing command output window. It remains blank. However, if you open up a new output window then it shows the previous output.
