### ISSUE TITLE
Blank error messages in code block with long message

### ISSUE THREAD

**Issue by charliva** [FPGAwars/icestudio#307]
I'm detecting new error message problems with some kind of reported errors.

**Comment by charliva** [comment]
Fixed yet and pull request done.
![test_blank_error2_done](https://user-images.githubusercontent.com/6904865/52494821-45c0d200-2bcf-11e9-9e65-fe1fc34d1c98.jpg)

**Comment by Obijuan** [comment]
Thanks! Estás on fire! :-D
