### ISSUE TITLE
Build only Linux executable

### ISSUE THREAD

**Issue by BryceBeagle** [FPGAwars/icestudio#309]
I'm trying to turn this project into a package for Arch Linux.

Is there a way to build _only_ the Linux executable (not the AppImage) from source? Trying to run `npm run dist` (after commenting out the jshint grunt task in `gruntfile.js` to avoid #310) gives me an error about not having Wine installed. 

As I don't need a Windows build, I don't think this should be necessary.

**Comment by umarcor** [comment]
@BryceBeagle, you can patch `gruntfile.js` to overwrite `platforms` and `distCommands` just after:

https://github.com/FPGAwars/icestudio/blob/dcbbbb7f9e28fd74b129a3d1ac67e85a3886d58a/gruntfile.js#L16-L20

For example:

```js
    platforms = ['linux32', 'linux64'];
    distCommands = ['compress:linux32', 'compress:linux64'];
```

**Comment by cavearr** [comment]
hi @BryceBeagle ! it isn't a linux executable as is.  Icestudio uses nwjs. If you want to package icestudio for specific linux flavor, you can find some information at nwjs:

http://docs.nwjs.io/en/latest/For%20Users/Package%20and%20Distribute/#linux

Thanks!
