### ISSUE TITLE
Arduino orientado a objetos

### ISSUE THREAD

**Issue by jaso69** [FPGAwars/icestudio#311]
Buenas tardes.  Dada la potencia de las fpga, quizás seria interesante crear un lenguaje basado en arduino, dada la gran comunidad que existe y crear un lenguaje orientado a objetos con el lenguaje que usa arduino y procesamiento paralelo. Vamos un arduino 2.0, por llamarlo de alguna manera. Creo que seria la revolución que se demanda hoy en día. He empezado a crear algo parecido, pero me supera el tamaño del proyecto.
  Un saludo.

**Comment by cavearr** [comment]
Hola @jaso69  esta pregunta se sale fuera del ámbito de este proyecto. Si quieres ayuda, opiniones etc de este tipo de preguntas más amplias puedes dirigirte a nuestro grupo de Google que es un foro menos especializado:

https://groups.google.com/forum/#!forum/fpga-wars-explorando-el-lado-libre

Gracias
