### ISSUE TITLE
Is any ECP5 board in plan?

### ISSUE THREAD

**Issue by goran-mahovlic** [FPGAwars/icestudio#320]
We would love to have support for ULX3S
https://hackaday.io/project/159108-ulx3s-powerful-ecp5-board-for-open-source-fpga

**Comment by drtrigon** [comment]
That would give us 2nd board with icestudio & Arduino IDE support, beside the Alhambra II (and similar): https://github.com/FPGAwars/icestudio/issues/321 and https://github.com/drtrigon/fpgarduino-icestorm

**Comment by janrinze** [comment]
prjtrellis is supported by apio.
So if the constraints file can be generated and the right version of nextpnr can be included, I don't see what could be the big hurdle here.

**Comment by Obijuan** [comment]
@mmicko has already added suport for ulx3s boards in the devel branch. We are working on it now

**Comment by cavearr** [comment]
At v0.5.1 dev branch we have support for ecp5 boards
