### ISSUE TITLE
FRONT: Nightly version. TAG property undefined

### ISSUE THREAD

**Issue by jcarolinares** [FPGAwars/icestudio#323]
When you create a tag for the first time, the property "Choose a color" is showed properly.

However, after the creationf of the tag, if you enter again, the text of "Choose a color" appears as "Undefined"
![bug](https://user-images.githubusercontent.com/7687624/57788987-589bf300-7738-11e9-9e60-ea1fefa1b0ee.png)

**Comment by Obijuan** [comment]
I've reproduced the bug too. Bug confirmed!

Thanks Julian!  :-)

**Comment by cavearr** [comment]
Fixed on v0.5.1
