### ISSUE TITLE
No se crea nuevo archivo en blanco

### ISSUE THREAD

**Issue by angelmicelti** [FPGAwars/icestudio#327]
He observado que, teniendo un proyecto abierto, al elegir la opción _Archivo > Nuevo_, no se abre un proyecto en blanco, sino que se carga el mismo proyecto que ya teníamos.
Por tanto, para crear un proyecto en blanco tengo que cerrar todas las ventanas abiertas e iniciar IceStudio.
Aparte de eso, en la barra de título de la nueva ventana, el logotipo de IceStudio es sustituido por otro icono de color negro (creo que esto ya ha sido reportado anteriormente).
Estoy usando la versión 0.4.0 dev nightly en Windows 10.

**Comment by cavearr** [comment]
Corregido en la versión 0.5.1
