### ISSUE TITLE
[Feature] Add Fomu board 

### ISSUE THREAD

**Issue by renatorabelo** [FPGAwars/icestudio#330]
It would be nice to have Icestudio supporting fomu FPGA as an option to select from the boards menu ( Lattice ICE40UP5K already supported). 

https://www.crowdsupply.com/sutajio-kosagi/fomu

**Comment by Jesus89** [comment]
Sure! We should add the board first here: https://github.com/FPGAwars/apio

**Comment by fancellu** [comment]
I think the README.md needs to be added to add the Fomu

Icestudio offers the Fomu on the board selection UI

**Comment by Obijuan** [comment]
This board is fully supported. I will close this issue
