### ISSUE TITLE
[Feature] Add ULX3S board

### ISSUE THREAD

**Issue by langster1980** [FPGAwars/icestudio#336]
I'm using the ULX3S board from the guys at Radiona!  Its a really cool piece of kit and I know you guys got it working with APIO in previous versions.  It would be very nice if this board could be added to Ice studio.

Cheers

Alex

**Comment by drtrigon** [comment]
Duplicate of #320

**Comment by Obijuan** [comment]
The updates about this issue will be in the #320 
I will close this issue
