### ISSUE TITLE
adicionar placa blackice_MX

### ISSUE THREAD

**Issue by edferoca** [FPGAwars/icestudio#342]
hola a todos, hace poco salio la  placa [blackIce_MX](https://github.com/folknology/IceCore) sucesora de la  blackIce II  y me gustaría  poder ayudar  a implementarlo en iceStudio; no es tan diferente a la  blcakIce II pero no se como hacer que icestudio la reconozca y programe (pues colocarla en el menú no es tan difícil). ¿alguien tiene alguna idea o nos podríamos ayudar para agrandar esta buena Herramienta ?

**Comment by Obijuan** [comment]
Ya está soportada en el pull request #350
