### ISSUE TITLE
Problema con atajos de teclado.

### ISSUE THREAD

**Issue by braincodec** [FPGAwars/icestudio#35]
Cuando modificas una etiqueta de un bloque, si haces un CTRL+C (por ejemplo, para copiar esa etiqueta), además te hace un clonado del bloque ;)

Lo mismo sucede si estás en un bloque de código, al hacer un CTRL+C te hace un clonado del bloque.

También, cuando estás modificando una etiqueta, si presionas CTRL+SUPR, te muestra la ventana de verificación de borrado del bloque actual.

**Comment by Jesus89** [comment]
Solucionado. Shortcuts desactivados cuando se muestra un diálogo prompt.

Además, el bloque código se deselecciona al clicar o editar en su contenido.

87a754b5e6cb0220a92dde943c9f62c8083f1b59
