### ISSUE TITLE
[BUG] HELP links are not opened in the browser

### ISSUE THREAD

**Issue by Obijuan** [FPGAwars/icestudio#366]
When clicking on the options of the Help, the web page does not appear

All the option that are linked to an external URL are not working:

* Help/View License
* Help/Documentation
* Help/Source code
* Help/Community Forum

![screenshot_7](https://user-images.githubusercontent.com/1286062/71404810-cba50a80-2633-11ea-830b-dc055a7dcec2.png)

**Comment by cavearr** [comment]
It's fixed!
