### ISSUE TITLE
[Help needed] Cannot build devel on macOS

### ISSUE THREAD

**Issue by nanoant** [FPGAwars/icestudio#367]
I am having a trouble to build icestudio `devel` on macOS. First of all node-v12.14.0-darwin-x64 does not work at all. Some packages fail to build on `npm install`. When using node-v10.18.0-darwin-x64 it builds but when doing `npm run dist` I get `Apio settings are in debug mode` error. If I disable this check I get:
~~~
Fatal error: Command failed: cache/toolchain/venv/bin/pip download --dest cache/toolchain/default-apio apio[blackiceprog,tinyfpgab,tinyprog]">=0.5.0,<0.6.0"
~~~
I am definitely missing something. How do I pull latest `apio`?

**Comment by cavearr** [comment]
Hi @nanoant ! Could you try with node 10.17.x version?

**Comment by Obijuan** [comment]
Please, try it again with the latest icestudio version. I will close this issue. Please, feel free to reopen it if the problem remains
