### ISSUE TITLE
ulx3s-8f, lpf lpf not found. iverilog not recognized in windows

### ISSUE THREAD

**Issue by agnunez** [FPGAwars/icestudio#372]
In Windows 10, after clone latest develop branch and trying npm install, works but throws this errors:
d:\fpga\icestudio\node_modules\iltorb\src\enc\stream_encode.cc(109): error C2661: 'v8::Value::BooleanValue': no overloaded function takes 0 arguments [D:\fpga\icestudio\node_modules\iltorb\build\iltorb.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\fpga\icestudio\node_modules\iltorb
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok

After that, npm start works. Choose ulx3s-85f, ask for toolchain update. Updates works, but after that, trying to verify a simple sketch, throws the following error:

WARNING: no LPF file found (.lpf) iverilog -o hardware.out -D VCD.output 

c:\Users\anunez\.icestudio\apio\packages\... yosys\share\yosys/ecp5/cell_sim.v main.v "iverilog" is not recognized as internal or external command. operable command or batchfile. scons: *** [hardware.out] Error 1

**Comment by cavearr** [comment]
I'm closing this issue because is the same that #375, replied now.

Thanks!
