### ISSUE TITLE
Optionally use tools available on the host

### ISSUE THREAD

**Issue by eine** [FPGAwars/icestudio#381]
Development of dependencies for synthesis and P&R (yosys, nextpnr, icestorm, prjtrellis) is significantly faster than that of icestudio and apio. It seems difficult to revert (yet to equalize) it, given the limited human resources in FPGAwars. As a result, users of icestudio are tied to latest stable releases of the tools distributed through apio. While it is good enough for entry-level users, it falls short for more experienced users.

I'd like to request the installation/location of the tools to be optionally decoupled from icestudio (the frontend/GUI editor). This request is similar and compatible with #370. However, unlike #370, I think it is ok to have a default toolchain installed, as long as it is possible to change it in the settings.

Moreover, project GHDL provides multiple docker images including yosys, nextpnr, icestorm, prjtrellis and symbiyosys. These, which are always built from `master` and updated weekly (at most), work on GNU/Linux, Windows and macOS. Should the location/execution commands of the tools be configurable, it would be straightforward to use icestudio along with those images. See e.g. https://github.com/antonblanchard/microwatt/blob/master/Makefile.synth

**Comment by juanmard** [comment]
@Obijuan Why does it close for no reason?
