### ISSUE TITLE
Use nextpnr instead of arachne

### ISSUE THREAD

**Issue by daveshah1** [FPGAwars/icestudio#391]
arachne-pnr is not maintained and has a few bugs that aren't likely to be fixed (indeed it may well bitrot over time as compilers change and further latent bugs appear).

Moving to nextpnr would be sensible for the long term and also gain timing driven place and route, shorter build times for larger designs, and timing analysis built in.

**Comment by Obijuan** [comment]
thanks for the issue!

Yes, Icestudio already uses Nextpnr in the 0.5.1-nightly development version (thanks to @mmicko). The next release will come with it

I will close this issue
