### ISSUE TITLE
Use python3 instead of requiring python 2.7 on windows?

### ISSUE THREAD

**Issue by wgaylord** [FPGAwars/icestudio#393]
Is it possible to use IceStudio with python3 instead of python 2.7? 

The program says Python 2.7 is required but I don't have it on my system anymore because I don't want to be programming for EOL software..

**Comment by jmi2k** [comment]
AFAIK the nightly versions do require Python 3.x

**Comment by wgaylord** [comment]
Can't it be told to use an already installed python 3? Or does it have a max supported version? I have 3.8 installed on my system.

**Comment by cavearr** [comment]
Download the last nightly version at:

https://icestudio.io

If you hace python 3.8 you dont need to install it.

**Comment by wgaylord** [comment]
If I don’t let it install the 3.7 it wants to is tall it just closes the installer.

**Comment by cavearr** [comment]
I'm reviewing it, i tell you soon

**Comment by GnarlyDave** [comment]
windows64 bit: 
I upgraded from a working 0.5 (with python 2.7.13 and 3.8.2) to to 0.5n200403, the installer wanted to install 3.7.4 ... but if it installed it, pypthon 3.7.4 doesn't appear in the windows list of installed programs.
now it complains about the toolchain being broken, but Tools->ToolChain->Install gives error 'At least Python 3.5 is required'

**Comment by cavearr** [comment]
Hi! there is an error at the last binary. We are repacking now and update this issue when new binary will be up to date.

Thanks a lot !!

**Comment by cavearr** [comment]
Hi @GnarlyDave  there is a new windows binary at https://icestudio.io for nightly version with this problem fixed.

I'm recomend you uninstall first icestudio and python in your computer. Then reinstall icestudio and it will install the correct python version.

Thanks!
