### ISSUE TITLE
warning to console

### ISSUE THREAD

**Issue by GnarlyDave** [FPGAwars/icestudio#400]
if $HOME/.icestudio exists, but 
$HOME/.icestudio/collections doesn't exist

utils.js:439 Error: ENOENT: no such file or directory, scandir 'C:\Users\Dave\.icestudio\collections'
    at Object.readdirSync (fs.js:808)
    at Object.findCollections (utils.js:432)
    at Object.loadInternalCollections (collections.js:28)
    at Object.loadAllCollections (collections.js:15)
    at app.js:46
    at utils.js:1247
    at profile.js:45

I'd fix it myself, but it's 20 years since I did server side javascript and I'm still learning node.js :)

**Comment by cavearr** [comment]
Thanks! Today i’m fixing it!

**Comment by cavearr** [comment]
Now it's fixed on development branch, sorry for the delay!
