### ISSUE TITLE
Build fails if design contains default output

### ISSUE THREAD

**Issue by jdeitmerg** [FPGAwars/icestudio#402]
Hi,

when adding a Basic->output FPGA pin to the design and **not** changing the pin in the dropdown, the build will fail. It will work once after temporarily selecting  a different pin in the dropdown.

This will be especially frustrating for beginners with a TinyFPGA BX, as the default output is the LED.
Also, the error popup is empty (this was different some versions ago):

![default_output_build_error](https://user-images.githubusercontent.com/7459936/80193001-59abf480-8618-11ea-92dd-9e938ba598a7.png)

apio command output:
```
set APIO_HOME_DIR=C:\Users\jonas\.icestudio\apio& "C:\Users\jonas\.icestudio\venv\Scripts\apio.exe" build --board TinyFPGA-BX -p "C:\Users\jonas\AppData\Local\Temp\icestudio-4996RrMLRDw8Owu1"

[Fri Apr 24 10:30:53 2020] Processing TinyFPGA-BX
--------------------------------------------------------------------------------
yosys -p "synth_ice40 -json hardware.json" -q main.v
nextpnr-ice40 --lp8k --package cm81 --json hardware.json --asc hardware.asc --pcf main.pcf -q
ERROR: expected PCF syntax 'set_io cell pin' (on line 3)
ERROR: Loading PCF failed.
0 warnings, 2 errors
scons: *** [hardware.asc] Error -1
========================= [ ERROR ] Took 4.80 seconds =========================
```

I'm on Version 0.5.1n200403, Apio 0.5.4

**Comment by Obijuan** [comment]
Thanks for the report!  You are right. This is very bad for beginners (which are the main target for icestudio)

As a quick and dirty fix I've changed the initial pin name to NULL, so that you are forced to change it to the pin you want

The bug on error reporting is still there. I am working on that

![Peek 2020-04-25 18-12](https://user-images.githubusercontent.com/1286062/80284787-e0e48f80-8720-11ea-81f0-2500f368210f.gif)

**Comment by Obijuan** [comment]
Bug fixed! (in the development version)

![Peek 2020-04-26 13-45](https://user-images.githubusercontent.com/1286062/80306564-61a89780-87c4-11ea-89e0-75a0c53ca82b.gif)

**Comment by jdeitmerg** [comment]
Thanks for the fix. Awesome response time!
