### ISSUE TITLE
RGB Led Driver Support (UPduino v1)

### ISSUE THREAD

**Issue by ertgtct** [FPGAwars/icestudio#405]
Hello, Icestudio is really nice work so far.
I'd like to use it with a UPduino v1, but noticed, that the "SB_RGBA_DRV" module cannot be instantiated. But its use is mandatory, because the RGB LED itself is not current regulated. Is it possible to add support for it?
thank you in advance.

**Comment by ertgtct** [comment]
It seems, that the new nightly build now instantiates the SB_RGBA_DRV block.

**Comment by Obijuan** [comment]
I do not have an upduino board, so I will wait for you to test it and close the issue  
Thanks! :smile:

**Comment by ertgtct** [comment]
It’s working, the led and FPGA don’t seem to get hot.

**Comment by ertgtct** [comment]
It’s working, the led and FPGA don’t seem to get hot.
