### ISSUE TITLE
Unsupported platform for grunt-appdmg@1.0.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

### ISSUE THREAD

**Issue by AbsorbedInThought** [FPGAwars/icestudio#410]
I can't configure icestudio for development on either Windows 10 or Ubuntu 16.04. I always get the unsupported platform error.

Log file:
94 verbose node v10.17.0
95 verbose npm  v6.11.3
96 error code EBADPLATFORM
97 error notsup Unsupported platform for grunt-appdmg@1.0.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
98 error notsup Valid OS:    darwin
98 error notsup Valid Arch:  any
98 error notsup Actual OS:   win32
98 error notsup Actual Arch: x64
99 verbose exit [ 1, true ]

**Comment by cavearr** [comment]
This is fixed in development version!
