### ISSUE TITLE
Cannot find iceFUN in board select list but it is supported by apio

### ISSUE THREAD

**Issue by dabrams** [FPGAwars/icestudio#418]
As I said in my post I **am** running the nightly build. I also am running apio 0.5.4 (my original post was wrong - sorry I did not know where to find the version) and iceFUN is NOT appearing so I do not think the issue is closed yet.  I am running the Windows 64bit build.

![image](https://user-images.githubusercontent.com/508038/83793423-8406be00-a66a-11ea-9c26-45bb875e7958.png)

![image](https://user-images.githubusercontent.com/508038/83793441-88cb7200-a66a-11ea-9ea8-3d363b6f8adb.png)

![image](https://user-images.githubusercontent.com/508038/83793557-b9131080-a66a-11ea-9231-5498e73b57c0.png)

**Comment by Obijuan** [comment]
The iceFun is already available in the latest icestudio (0.8.2w)
I will close this issue
