### ISSUE TITLE
icestudio on a Raspberry Pi

### ISSUE THREAD

**Issue by rockyjsquirrel** [FPGAwars/icestudio#426]
How did you run icestudio on a raspberry pi?
I've been trying for a while. hangs up in npm install, wrong version and such, then lots of errors which end up saying there is nothing wrong with npm. :(

Any chance you can release an SD Card image of that?

BTW, Awesome app for FPGAs !!!

**Comment by cavearr** [comment]
Hi!! for the moment icestudio not works in raspberry pi but we are working on it  : )

**Comment by rockyjsquirrel** [comment]
I know you closed the issue but this yuotube video is where I got my information.
   
  
  
   
  
  
   https://www.youtube.com/watch?v=ATtrY0CNmGw
  
  
   
  
  
   Thanks anyway for repsonding.
   
  
  
   
  
  
   
  
  
   On July 29, 2020 at 5:23 AM Carlos Venegas Arrabé <notifications@github.com> wrote: 
   
   
   
   Hi!! for the moment icestudio not works in raspberry pi but we are working on it : )

**Comment by cavearr** [comment]
Yes this video is an old and primal version of icestudio, but now  it is not possible to run icestudio on raspberry pi, but very soon will be work, we are working in this way.

I'm maintaining this issue opened !

**Comment by flegmatik** [comment]
Any news on this?

**Comment by cavearr** [comment]
Hi! now you could download icestudio for linux arm64! https://downloads.icestudio.io
