### ISSUE TITLE
Program crashes when using "Add as block" 

### ISSUE THREAD

**Issue by androng** [FPGAwars/icestudio#431]
When adding the file "counter.ice" to "counter-to-serial.ice" using "File > Add as block...", IceStudio 0.5.0 crashes. 
Windows 10 Pro 64-bit v1909 
[Counter-to-serial.zip](https://github.com/FPGAwars/icestudio/files/5176453/Counter-to-serial.zip)

**Comment by androng** [comment]
Side note: program also crashes when copying and pasting a custom block such as "Counter" or "32-bit parallel-to-serial"

**Comment by cavearr** [comment]
Try with the nightly version (really is more stable than "stable" version): 

[ https://github.com/cavearr/icestudio-nightly/raw/master/0.5.1n200523/icestudio-0.5.1n200523-win64.exe | https://github.com/cavearr/icestudio-nightly/raw/master/0.5.1n200523/icestudio-0.5.1n200523-win64.exe ] 



De: "Andrew" <notifications@github.com> 
Para: "FPGAwars" <icestudio@noreply.github.com> 
CC: "Subscribed" <subscribed@noreply.github.com> 
Enviados: Viernes, 4 de Septiembre 2020 20:48:22 
Asunto: [FPGAwars/icestudio] Program crashes when using "Add as block" (#431) 





When adding the file "counter.ice" to "counter-to-serial.ice" using "File > Add as block...", IceStudio 0.5.0 crashes. 
Windows 10 Pro 64-bit v1909 
[ https://github.com/FPGAwars/icestudio/files/5176453/Counter-to-serial.zip | Counter-to-serial.zip ]

**Comment by cavearr** [comment]
This should be fixed in the last wip, close the issue , if you detect in the last wips reopen please.
