### ISSUE TITLE
Serial terminal option to choose newline codes

### ISSUE THREAD

**Issue by aalku** [FPGAwars/icestudio#442]
I think the serial terminal plugin needs an option to choose newline codes (\r, \n, \r\n) just like Arduino serial monitor.

I just thought "Obijuan's RISC-V-FPGA icestudio port" serial reception was not working because test.c example expects \r as newline and I guess icestudio serial terminal does not send \r on Windows. With Arduino serial monitor it worked. 😅

**Comment by cavearr** [comment]
In the last WIP, this featured is added.

Thanks @TimRudy for the reminder!
