### ISSUE TITLE
Add support for Upduino 3.0

### ISSUE THREAD

**Issue by LovelyA72** [FPGAwars/icestudio#443]
The generation and upload process is almost identical to upduino 2.1 with a minor usb ID change
https://github.com/tinyvision-ai-inc/UPduino-v3.0/tree/master/RTL#instructions-for-icestorm-toolchain-programming

Thank you!

**Comment by LovelyA72** [comment]
Just tested with a develop branch clone, it works perfectly with my upduino 3.0!
Thanks!

**Comment by KyleLomen** [comment]
Update on Upduino 3.0 support: Commit 504813fd916724866e352e78151adb13c73e3356 rolled back the apio version to 0.5.4. This broke support for the Upduino 3.0, manually updating the toolchain to 0.5.5 will restore support.
