### ISSUE TITLE
Error with libgconf-2 while trying to run icestudio from main branch sources on Ubuntu 18.

### ISSUE THREAD

**Issue by aalku** [FPGAwars/icestudio#445]
I have an error with libgconf-2 while trying to run icestudio from main branch sources on Ubuntu 18.

npm start gets stuck on `Waiting...` and the app does not start.

Examining the logs I find it may be an issue with `nw`. That command I don't have in my system path but that's not the problem.
I find `nw `in `icestudio/node_modules/nw/bin/nw` but running it it seems to lack `libgconf-2.so` or something like it. I don't have the exact error anymore because I found a workarround.

That workarround is `sudo apt install libgconf-2-4`

After that `npm start` starts working.

I don't know how this dependancy issue should be fixed or documented in the installation procedure.

**Comment by alexcweiner** [comment]
same thing happens in Ubuntu 20.04.1 LTS. Same workaround works too.

**Comment by cavearr** [comment]
Hi alex! What repository are you cloning?

Could you paste the url of the repo?

Thanks!

----- Mensaje original -----
De: Alex Weiner <notifications@github.com>
Para: FPGAwars/icestudio <icestudio@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Enviado: Sat, 24 Oct 2020 04:54:35 +0200 (CEST)
Asunto: Re: [FPGAwars/icestudio] Error with libgconf-2 while trying to run icestudio from main branch sources on Ubuntu 18. (#445)

same thing happens in Ubuntu 20.04.1 LTS. Same workaround works too.

**Comment by alexcweiner** [comment]
I used the Linux 64 bit AppImage file available at https://icestudio.io/#lk-download

**Comment by cavearr** [comment]
Try Thais command to install the dependency:

sudo apt install libgconf-2-4

And then rin icestudio.

Tell is if it works!

----- Mensaje original -----
De: Alex Weiner <notifications@github.com>
Para: FPGAwars/icestudio <icestudio@noreply.github.com>
CC: Carlos Venegas Arrabé <carlos@magnitude.es>, Comment <comment@noreply.github.com>
Enviado: Sun, 25 Oct 2020 01:25:34 +0200 (CEST)
Asunto: Re: [FPGAwars/icestudio] Error with libgconf-2 while trying to run icestudio from main branch sources on Ubuntu 18. (#445)

I used the Linux 64 bit AppImage file available at https://icestudio.io/#lk-download

**Comment by Obijuan** [comment]
I think this bug is fixed and the issue can be closed. Feel free to reopen it you still get the same error
