### ISSUE TITLE
Editing a block without affecting others

### ISSUE THREAD

**Issue by AbsorbedInThought** [FPGAwars/icestudio#450]
I wanted to know if it's possible to change the code written inside a block without it affecting other blocks. What I mean is, let's say I have 2 AND blocks in my circuit. I edit the code inside one of them and when I save it, it changes the code inside the second AND block too.
I want the code to be only modified for that specific instance and not all other blocks that share that dependency. Is it possible? If not, is there something I can do? Or what script files would I need to change to develop this kind of functionality?

Thanks.

**Comment by cavearr** [comment]
Hi!, you need to "copy" and "clone" (in edit menu) then the "clone" block is independent from its parent.
