### ISSUE TITLE
Blackice MX support

### ISSUE THREAD

**Issue by defcon8** [FPGAwars/icestudio#453]
Hi,

Is the Blackice MX supported in Icestudio on Mac?

Kind regards,
Bastiaan

**Comment by Obijuan** [comment]
Yes. Use the  nightly build: 0.5.1-n201009. You can download it from [Here](https://icestudio.io/#lk-download)

![blackice-icestudio](https://user-images.githubusercontent.com/1286062/99143690-cb549a00-265f-11eb-97d2-03212f9fc215.png)
