### ISSUE TITLE
[Dev-0.5.1n201120] Invalid project format when examples are open

### ISSUE THREAD

**Issue by Obijuan** [FPGAwars/icestudio#457]
This is related to issue #456

If the icezum alhambra board is selected and an example for the default collection is opened, the error message "Invalid project format" is shown

The example can be build and upload to the board (it works ok) but the error message makes you feel confused

![Peek 2020-11-21 08-01](https://user-images.githubusercontent.com/1286062/99870088-905ae500-2bd0-11eb-943f-47814041e9cc.gif)

**Comment by cavearr** [comment]
This is the same bug than #456 .

Stay open until you confirm that works.

**Comment by Obijuan** [comment]
Thanks @cavearr !  It is fixed! 😀️
