### ISSUE TITLE
fecha siguiente distrubición de icestudio??

### ISSUE THREAD

**Issue by manuelpas** [FPGAwars/icestudio#464]
en la proxima distrubición de icestudio se instalara apio 0.6.0 por defecto
cuando es la siguiente?

**Comment by manuelpas** [comment]
no ace falta. encontre como actualizar en twitter: https://twitter.com/JManuarrabal/status/1333885431373586432

[![](https://pbs.twimg.com/media/EoMH4tEW8AMlkOy?format=png&name=900x900)](https://twitter.com/juanmard/status/1333918926166745088/photo/1)

**Comment by cavearr** [comment]
Hola esta imagen que lanzas es de un fork de icestudio, si estás usando esa versión para cualquier duda dirígete a las issues de ese fork ya que es distinto del proyecto oficial.

**Comment by manuelpas** [comment]
la pregunta fue del proyecto oficial pero la ultima apio no esta solo en la nightly
