### ISSUE TITLE
board request: Support for mojo-v3

### ISSUE THREAD

**Issue by KROIA** [FPGAwars/icestudio#465]
Hi, I would like to test icestudio but my mojo board isn't supported.
I don't know how to manually add a board so can somone help me with this?

Board: https://alchitry.com/products/mojo-v3

**Comment by Jesus89** [comment]
Hi. I'm afraid this board can not be integrated with Icestudio since it uses a Spartan FPGA (not supported by the open-source toolchain "yet"). However, if you want to use icestudio, the same manufacturer provides the board "Alchitry Cu", which is already supported :)

**Comment by KROIA** [comment]
okey thanks for this info
