### ISSUE TITLE
ERROR : npm run dist

### ISSUE THREAD

**Issue by albertlu2013** [FPGAwars/icestudio#471]
I run "npm run dist" get the error as :

~/icestudio$ npm run dist

> icestudio@0.5.1-n201120 dist /home/albertlu/icestudio
> grunt dist

Running "checksettings" task

Running "jshint:all" (jshint) task

   app/scripts/factories/error.js
      4 |    return function myExceptionHandler(exception, cause) {
             ^ Missing "use strict" statement.
   app/scripts/libs/Icestudio/Core/IceCollection.js
      8 |    this.fs = new IceHD();
                           ^ 'IceHD' is not defined.
      1 |class IceCollection {
               ^ 'IceCollection' is defined but never used.
   app/scripts/libs/Icestudio/Fuse/IceHD.js
      1 |class IceHD {
               ^ 'IceHD' is defined but never used.
   app/scripts/services/collections.js
     20 |    const DEFAULT = '';
                   ^ 'DEFAULT' is defined but never used.
     21 |    const MAX_LEVEL_SEARCH = 20;
                   ^ 'MAX_LEVEL_SEARCH' is defined but never used.
     53 |    function getCollection(name, path, children) {
                      ^ 'getCollection' is defined but never used.
     13 |     let iceColl= new IceCollection({
                               ^ 'IceCollection' is not defined.

>> 8 errors in 37 files

**Comment by cavearr** [comment]
Fixed ! thanks!
