### ISSUE TITLE
Unable to upload program to iCESugar v1.5

### ISSUE THREAD

**Issue by hhhhljp** [FPGAwars/icestudio#487]
I can verify and build my project normally ，and *.bin file can be generated normally.
But I cannot upload the program to my iCESugar through icestudio
iCESugar has a on board debugger named iCELink (base on STM32F1).And I can only upload my program through the drag-and-drop function of iCELink.
and the command output is Garbled:
'icesprog' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
scons: *** [upload] Error 1

**Comment by qpeters** [comment]
@hhhhljp is this fixed in the latest stable release v0.6.0? https://github.com/FPGAwars/icestudio/releases/tag/v0.6.0

**Comment by hhhhljp** [comment]
Thank you. Everything's working now with 0.6.0
