### ISSUE TITLE
How to modify the iceFUN board target frequency - from 12MHz to 100MHz?

### ISSUE THREAD

**Issue by John-Westlake** [FPGAwars/icestudio#488]
I've modified a iceFUN PCB with a 100MHz FPGA clock (for the hx8k  - the PIC still uses the 12MHz for USB etc).

How do I update the target Frequency to 100MHz (from the iceFUN standard 12MHz) so that the icestudio toolchain is aware of the higher frequency 100MHz clock?

**Comment by cavearr** [comment]
the same as #554
