### ISSUE TITLE
icestudio-0.5.1w210224-win64 doesn't export ULX3 valid bitstream file

### ISSUE THREAD

**Issue by benitoss** [FPGAwars/icestudio#489]
When you export a bitstream in icestudio-0.5.1w210224-win64 the file generated has the same size for different ECP5 models.
So that is not possible
is the bitstream export working in any ULX3 model?

Thanks

**Comment by qpeters** [comment]
@benitoss is this fixed in the latest stable release v0.6.0? https://github.com/FPGAwars/icestudio/releases/tag/v0.6.0

**Comment by Obijuan** [comment]
I think this issue is fixed. Can you please try it on the latest wip version?  You can download it from here:

[@jojo535275](https://downloads.icestudio.io/)
