### ISSUE TITLE
icestudio 0.5.1n210107 linux64 nighty

### ISSUE THREAD

**Issue by sasasuio** [FPGAwars/icestudio#490]
Hola,

A ejecutar la versión nighty en linuxmint 64 bits 0.5.1n210107 arroja el siguiente error en segundo plano al tratar de instalar el toolchain:

command failed: /usr/bin/python3.8 -m venv "home/username/.icestudio/venv"

luego queda en 10%, hice un rollback a la anterior y funciona bien :) 

Espero sirva de ayuda,

**Comment by Obijuan** [comment]
Tienes que instalar el entorno virtual de python. Si tu distribución de Linux es Ubuntu, ejecuta este comando desde la línea de comandos:

sudo apt install python3-venv

Luego arranca la última versión de Icestudio

**Comment by sasasuio** [comment]
> Tienes que instalar el entorno virtual de python. Si tu distribución de Linux es Ubuntu, ejecuta este comando desde la línea de comandos:
> 
> sudo apt install python3-venv
> 
> Luego arranca la última versión de Icestudio

Funciona perfectamente! Gracias, Obijuan ;)
