### ISSUE TITLE
Can't install due to adam-lynch/node-temp missing package.jso

### ISSUE THREAD

**Issue by Phil67ago** [FPGAwars/icestudio#505]
Hi!

[user ~]$ git clone https://github.com/FPGAwars/icestudio.git
[user ~]$ cd icestudio
[user ~]$ npm install
npm ERR! code ENOLOCALFrom:

npm ERR! Could not install from "node_modules/nw-builder/temp@github:adam-lynch/node-temp#remove_tmpdir_dep" as it does not contain a package.json file.

I'm not so familiar with npm but https://github.com/adam-lynch has no 'node-temp'???

npm version: npm-6.14.13-1.14.17.0.1.fc34.x86_64

**Comment by Obijuan** [comment]
Make sure you have installed the correct node version (it should be 10.17.0)

You can find more information on this link: https://github.com/FPGAwars/icestudio/wiki/Icestudio-development-version

**Comment by Phil67ago** [comment]
I solved it by deleting 'package-lock.json'
[user ~]$ cd icestudio
[user ~]$ rm package-lock.json
[user ~]$ npm install
launch:
[user ~]$ npm start

node version: nodejs-14.17.0-1.fc34.x86_64
