### ISSUE TITLE
ctrl-z for undoing edits in code text blocks

### ISSUE THREAD

**Issue by SiccoDwars** [FPGAwars/icestudio#511]
Both on Mac and Win10, hitting CTRL-Z in an open for text edits block is devastating and seems to put Icestudio in a mode where .ice project file can no longer be saved (is no longer being saved, what’s saved is the pre ctrl-z version it seems).

Is this just me?

Ctrl-z does work for undoing graphical edits in block diagrams.

**Comment by cavearr** [comment]
solved is the same as #481
