### ISSUE TITLE
Add NEORV32 CPU example for icestudio

### ISSUE THREAD

**Issue by qpeters** [FPGAwars/icestudio#516]
NEORV32 is an open source (BSD-3-Clause License) 32 bit RISC-V core and System on Chip with good documentation :smiling_face_with_three_hearts: https://stnolting.github.io/neorv32/. Multiple Open Source FPGA boards are supported: UPduino, Fomu, iCESugar, OrangeCrab... It is very interesting for learning:

![](https://stnolting.github.io/neorv32/img/neorv32_processor.png)

![](https://stnolting.github.io/neorv32/img/neorv32_bus.png)

![](https://stnolting.github.io/neorv32/img/neorv32_cpu.png)

It would be awesome :star_struck: to have it available in the list:

- https://github.com/FPGAwars/icestudio#risc-v-cpu
- https://github.com/FPGAwars/icestudio#z80-cpu
- https://github.com/FPGAwars/icestudio#hack-zpu-nand2tetris-project

**Comment by Obijuan** [comment]
Currently there is no icestudio version of that project, so it cannot be shown as an example
