### ISSUE TITLE
Allow click / shift+click to select (not just box drag)

### ISSUE THREAD

**Issue by tschundler** [FPGAwars/icestudio#522]
It look me minutes to figure out how to delete a component. I expect to click then press delete or x or something. And nothing worked until I realized click+drag makes a selection box.

For consistency with other programs, in addition to box-select, clicking a component should select it, and shift+click to select multiple. (Or meta/ctrl + click for multiple)

Then click + delete would work as expected

**Comment by Obijuan** [comment]
I agree with you. Just one click should be enough to select a component
I've checked your pull-request and it works ok in my linux  
Let's wait for @cavearr to test it and merge it
Thanks for your contributions!
