### ISSUE TITLE
Caracteres extraños en el path

### ISSUE THREAD

**Issue by Democrito** [FPGAwars/icestudio#526]
Según parece, cuando hay caracteres extraños en el path el comportamiento de Icestudio sufre inconsistencias, como por ejemplo que no aparece los iconos de los módulos. Sucede por ejemplo si en el path contiene la almohadilla '#'.

Saludos y muchas gracias!

**Comment by cavearr** [comment]
Cierro esta issue, este problema es debido a limitaciones de nodejs y compatibilidad con el sistema operativo.
Existía un bug relacionado con puntos en el path que ya está resuelto.
