### ISSUE TITLE
"A new stable version is available"

### ISSUE THREAD

**Issue by Stereocheck** [FPGAwars/icestudio#545]
This pops up every time I open Icestudio, no matter which stable version I am using. I am using 0.7, which is the most recent stable version as far as I understand?

P.S. The website at https://icestudio.io/#lk-download still references version 0.6 downloads as the stable release. 

OS: Windows 10/11
Version: 0.7

**Comment by Obijuan** [comment]
Hi @Stereocheck !  A new stable release is available (0.8). The bug you mentioned should be now fixed, so you should no longer see the message "A new stable version is available"

I will keep this issue open until @cavearr updates the links to point to the new 0.8 stable downloads

Thanks for your feedback

**Comment by cavearr** [comment]
The links are updated!
