### ISSUE TITLE
[Feature] Add the xor logic gate by Carlos Santiago Díaz

### ISSUE THREAD

**Issue by Obijuan** [FPGAwars/icestudio#55]
Add the xor logic gate by Carlos Santiago Díaz, submitted to the FPGAwars list:

https://groups.google.com/d/msg/fpga-wars-explorando-el-lado-libre/FJSynyeprPA/_BqdIeBUDAAJ

**Comment by Jesus89** [comment]
Block added! d361ded1ef19fcd100373644441e1a6c646905f1

It will be available in the next release.
