### ISSUE TITLE
File extension

### ISSUE THREAD

**Issue by zipotron** [FPGAwars/icestudio#611]
Hello, I just detected that the file extension and the "code tagging" in Github of this project is interfering with another.
Check this issue: https://github.com/sylefeb/Silice/issues/206#issue-1105465885
Also I could see that Github is identifying the IceStudio code as a "Slice".
Thanks for this awesome project.

**Comment by cavearr** [comment]
Hi @zipotron!! thanks for advice! Silice is an awesome project and we collide with the same extension.

I'll try to investigate how to fix with Github.

I'm maintaining this thread open while i'm investigating.

Thanks again.

**Comment by zipotron** [comment]
With pleasure! The people of Silice seams to move their file extension (as can be seen in their issue) Good luck with the Github parser!

**Comment by cavearr** [comment]
yes! i'm reading the thread, for the moment Icestudio maintains the .ice extension, maybe in the future could change for other that not collides.

**Comment by zipotron** [comment]
No needed to change anymore...
