### ISSUE TITLE
Problema al caragar una programa en Alhambra II con mi mac

### ISSUE THREAD

**Issue by opelectron** [FPGAwars/icestudio#613]
Seguro que es un problema recurrente pero tengo problemas para poner operativa mi Alhambra II en mi mac. Cuando intento cargar un programa con icestudio .

He seguido todos los hilos pero no consigo solucion .

Saludos.

<img width="412" alt="Captura de pantalla 2022-01-28 a las 2 14 04" src="https://user-images.githubusercontent.com/66943309/151604813-09d6911f-a25f-44de-a7fd-45377802f51a.png">
me sale el siguiente error

**Comment by opelectron** [comment]
He actualizado python 3.9
He actualizado pip3 i apio 0.8.1

Icestudio no detectecta la placa , no aparece en el listado de puerto .
versión estable
version no estable

Ya no se que hacer.

macos bigsur 11.6.2

**Comment by cavearr** [comment]
Cierro este issue, si persiste el error o necesitas ayuda , reábrela,
