### ISSUE TITLE
Board request UPduino v3.1

### ISSUE THREAD

**Issue by AsynchronousParallel** [FPGAwars/icestudio#617]
Hello,
           I would like to use ICEstudio with my UPduino v3.1

**Comment by Xenador77** [comment]
[The nightly builds](https://downloads.icestudio.io/) have Upduino 3.1 support, just isn't a part of the stable branch release yet
[TinyVision.ai/upduino_3.1 discord](https://discord.gg/Y5AJwH82Fs) is very helpful when troubleshooting/debugging etc
