### ISSUE TITLE
No internect connection when downloading toolchain

### ISSUE THREAD

**Issue by donnmphone** [FPGAwars/icestudio#619]

**Comment by LBertrandDC** [comment]
Possibly a duplicate of #513 ?

**Comment by Obijuan** [comment]
@donnmphone , could you please try the latest wip? You can download it from here:
https://downloads.icestudio.io/

**Comment by donnmphone** [comment]
Thx! It doesn't work! It couldn't download the tools chain  !

**Comment by jojo535275** [comment]
I had this problem once when my VPN was connected !
So, i f you have one, try disconecting just for the toolchain download/installation!

And if it doesnt do the job, you can try[ installing the toolchain manually](https://github.com/FPGAwars/icestudio/wiki/Installing-the-Toolchains-from-outside-icestudio)!

If you manage to solve the problem on your machine, please let us know whaht worked for you !

**Comment by cavearr** [comment]
I will keep the issue open for a few days in case you give me feedback and if you do so later and find it closed, open it without hesitation.

**Comment by cavearr** [comment]
I'm closing the issue for not having reply and not be a global problem detected in other users.

If you need help about it , reopen it please!
