### ISSUE TITLE
Blocks menu missing from icestudio

### ISSUE THREAD

**Issue by matthewrobe** [FPGAwars/icestudio#624]
Hello, I'm having problems with icestudio 0.9.0 on win10 21H2 build 19044:1586 

I'm missing the Blocks section of the menu bar, see screen cap.
![noblocks](https://user-images.githubusercontent.com/39923262/160679062-81cfb2f9-efc2-4afd-ab1b-7ca49afd388f.png)
Had the nightly build installed and rolled back to the latest stable release.
does anyone have any ideas?

Many thanks
Matthew

**Comment by cavearr** [comment]
Ctrl+T open the new toolbox!  check it and tell us!

**Comment by matthewrobe** [comment]
Thanks, Found that :)
![with basic toolbox](https://user-images.githubusercontent.com/39923262/160681241-77708ffb-65cc-4131-b45d-3e8e2b3e98d8.png)
But can't locate the other Block items?

**Comment by cavearr** [comment]
the other blocks are on the right , when you could see "Default collection".

Try install the Jedi Collection https://github.com/FPGAwars/Collection-Jedi , that has a lot of blocks.

**Comment by matthewrobe** [comment]
Aha! Many thanks, don't know how I missed that :)

**Comment by Alfredo2591** [comment]
Tuve que desinstalar la version 9 pues no aparecia el panel basico.
Con la version 3 estable si que aparece.
Actualmente, no me reconoce la Alhambra 2, puede que se deba a tanta reinstalacion.

**Comment by Obijuan** [comment]
En la versión 9 la opción del menú básico está en un panel móvil de herramientas (disponible en la opción Editar/toolbox). También se activa con el atajo ctrl-T

**Comment by Alfredo2591** [comment]
Ok.Gracias.
No me reconoce la version 3 la Alhambra 2 y eso ....que la tengo en libusbk, actualmente acabo de instalar la 9 y voy a descargar la blockchain.
Anteriormente tenia la camara web, que la he desinstalado.
Espero conseguir que me reconzca la placa.

**Comment by Alfredo2591** [comment]
Me encuentro con que a la carga del hola mundo,..me da este error.
![Captura de pantalla (13)](https://user-images.githubusercontent.com/99606591/161301336-d11a0193-c402-43ad-9620-ca997a59fa7d.png)

**Comment by Alfredo2591** [comment]
Gracias por la información. 🤝👍🙏
No obstante estoy teniendo problemas con la versión nueve, me da error a la
hora de verificar.
Adjunto una captura de pantalla.

[image: Captura de pantalla (13).png]

**Comment by Obijuan** [comment]
I will close this issue, as it has been solved

@Alfredo2591 : Tu problema es el mismo que el de @Strauss77

Por favor, sigue las instrucciones indicadas aqui:

https://github.com/FPGAwars/icestudio/issues/494

Esta issue la cerramos porque el panel de Toolchain ya te aparece y sabes cómo sacarlo (no es un bug de icestudio)
