### ISSUE TITLE
Upload : fail not propagated

### ISSUE THREAD

**Issue by laulin** [FPGAwars/icestudio#627]
I just installed icestudio and related stuffs for playing with IceFUN. Everything was OK, GUI said the bitstream was uploaded ... but nothing happen on the board. After watching the terminal, it appears to be a right problem on /dev/ttyACM0 (error 13 -> sudo usermod -a -G dialout YOURUSER). 

So in this case, it sucessed but it failed.

**Comment by cavearr** [comment]
I'm closing the issue for not having reply and not be a global problem detected in other users.

If you need help about it , reopen it please!
