### ISSUE TITLE
How to update PCF ?

### ISSUE THREAD

**Issue by laulin** [FPGAwars/icestudio#628]
The PCF's icefun seems to have missing pins like RX (p73) and TX (p59) [see https://www.robot-electronics.co.uk/files/iceFUNdoc.pdf, last page]. How can I update the PCF to add this kind of pin ?

**Comment by cavearr** [comment]
Hi! You are running Icestudio from sources or you use a binary package?

**Comment by laulin** [comment]
Hello :)

I am using the binary package from icestudio.io, the stable one (0.9.0-1).

**Comment by cavearr** [comment]
If you have coding skills, you could modify it in app/resources/boards directory (in it you could find a directory for each board and in it you could find the pcf).

Once you modify it, you could do a pull request to the project, your contributions are very welcome!

If you don't have coding skills  we try to update as soon as possible.

Thanks!

**Comment by laulin** [comment]
Ok, i will try to figure out how to update the code and do a pull request.

Thank you for you help :)

**Comment by cavearr** [comment]
If you need any help , please tell me!
If you want to make the changes,  follow the instructions in the readme for development. Basically:
1) clone repository with git
2) execute npm install
3) make your changes
4) execute npm start to see if your changes works fine.
5) npm jshint   , to review if you make some format error.
6) commit your changes!

Thanks a lot and ask all of you need.

**Comment by laulin** [comment]
Ok i will read the README that carefully.
