### ISSUE TITLE
Icestudio: Board not connected

### ISSUE THREAD

**Issue by MeindlD** [FPGAwars/icestudio#630]
Hi Community,

I'm new to the topic of FPGA and Icestudio seems to be a good starting point for me.
So I purchased a iCE40 UltraPlus Breakout Board and downloaded Icestudio on my Windows 10 Client.
I installed Icestudio, the toolchain and the drivers as described in the "Quick Start" - Documentation.
But whenever I try to upload a file to the board I get the Message "Board iCE40 UltraPlus Breakout Board not connected".
J6 is in the position "PROG ICE", J7, J51 and J28 are closed, J11 is open (refer to https://www.latticesemi.com/Products/DevelopmentBoardsAndKits/iCE40UltraPlusBreakoutBoard).
I already changed the Notebook and tried a different breakout board, but the error message stays the same.
I have no idea, what else I could try.

Greetings,
Dominik

**Comment by Obijuan** [comment]
Now that I've manage to get access to a windows machine, I will take some more screenshots. This screenshot correspond to the driver installation (Tools/drivers/Enable). If the usb cable is ok, and you have passed the previous checks, connect the board. You will find the device "Lattice ICE40UP5K Breakout (Interface 0)"  (IT IS IMPORTANT TO BE THE Interface 0).  Select the libusK and click on Replace driver:

![imagen](https://user-images.githubusercontent.com/1286062/170199867-029078c0-add8-4e78-849e-148b2345e9e8.png)

It will take some time for windows to install the driver

After that you will see this window:

![imagen](https://user-images.githubusercontent.com/1286062/170200895-43a71218-b58e-4842-b823-cd596fae1a67.png)

Close the window. Now unplug the board and plug it again

**Comment by Obijuan** [comment]
This is the board with the previous circuit loaded (I've put some papers on the RGB led)

![20220525_091337](https://user-images.githubusercontent.com/1286062/170203642-b595f3d0-532e-41be-8455-844b2e0a18ac.jpg)

In this picture you can see the configuration of my jumpers:

![20220525_091414](https://user-images.githubusercontent.com/1286062/170203856-069ea5b5-3018-46ec-ae23-611e656665cf.jpg)

> **Note**
> The J6 should be in Flash position

But before all of this, check first your USB cable

**Comment by MeindlD** [comment]
Hey Obijuan,
first of all: Thanks for the detailed instructions!
So I removed the installed drivers and start again from the beginning to provide you the requested screenshots.
When I plug in the board, the following devices appear:
![image](https://user-images.githubusercontent.com/106069445/170209021-8ac1c88c-8d86-42c1-91d2-2fba94bbf01f.png)

So it seems, that my cable is ok (I changed it anyway). The device ID is the same as yours (0403/6010).
But when I try to install the driver, i experience a different behavior: My device is named USB<-> Serial converter
Do i have to install any software from Lattice in advance? The USB ID and the driver versions are the same as yours.
![image](https://user-images.githubusercontent.com/106069445/170211575-91966aa9-d823-4018-8c38-dc403c79eef2.png)

The driver installation succeeds:
![image](https://user-images.githubusercontent.com/106069445/170211982-b40accc2-81f0-49ce-863a-e0977d9c06b6.png)

After plugging the Board out an in again, the following devices appear:
![image](https://user-images.githubusercontent.com/106069445/170212703-944ffbf0-0260-4d6e-9b4d-4c064203202b.png)

When I now try to upload your example, i get the error message again:
![image](https://user-images.githubusercontent.com/106069445/170214156-9848d5f7-9ec8-429c-b718-1f3dbf617270.png)

The configuration of the jumpers should be the same:
![image](https://user-images.githubusercontent.com/106069445/170214776-07a2ddd1-c2ae-4828-a5c7-b99e05608480.png)

Do you have any idea, how to proceed?

Thanks in advance,
Dominik

**Comment by Obijuan** [comment]
ok, I see. As I am not a windows user/developer I really cannot help much. For whatever the reason your windows system cannot read the board information (it is not related to Icestudio, as Zadig (the driver installer) cannot see it either). So, the first step is trying to make Zadig see it

Maybe you could try to uninstall the USB serial converted A and try Zadig again. Does Zadig see it now? You should read "Lattice ICE40UP5K Breakout (interface 0)
Also try to unplug all the USB devices you can, just in case there is a kind of "interference" between them (who knows, some installed driver that is bothering the others...)
It will try it in Windows again and get more screenshots. I think I do not have the USB-Serial converter drivers... but I am not sure (Making drivers work in Windows is like magic. If you apply the correct spell it will work....)

**Comment by MeindlD** [comment]
I tried to remove the driver in several ways now:
First i uninstalled the device and activated the checkbox "Delete the driver software for this device".
![image](https://user-images.githubusercontent.com/106069445/170250671-b6964efd-9072-40a8-8494-2482aa6882fa.png)

Second i manually deleted the driver files listed for this device:
![image](https://user-images.githubusercontent.com/106069445/170251236-192257d6-e6c6-471f-80eb-67d2eba46682.png)

But when i disconnect the board and connect it again, the files appear and the driver is installed like it had never been deleted.

Additionally, i downloaded and installed the "Diamond Programmer" from Lattice with its drivers. Also no success.
The same drivers as before are installed, when i plug in the board.

This drives me nuts...

**Comment by TimRudy** [comment]
Hi Meind,

I had the same issue (FPGAwars issue #234), and tried all kinds of
software/driver and Zadig/install attempts, but it isn't a software issue,
it is an issue where you need to give Windows a kick by using an actual new
USB port or ID (that it assigns). I guess you already tried all the USB
ports on your machine? Now, to put a new USB hardware ID in its USB
hierarchy all you have to do is borrow a USB hub - bus-powered - for
example a 1-to-4 hub. (Another example is I had a remote USB port on a
monitor, and that worked.) With different hardware, you should get
different result. Windows can need a bit of magic (or give you a bit of
magic) like Obijuan said. Good luck!
  Tim

**Comment by MeindlD** [comment]
Hi Tim,
thanks for joining the discussion 😂
It's good to hear, that I am not the only person in the world with this problem.
According to what you proposed, i used the USB Hub in my monitor, aaaaaaaaaaaaand...

at least the error message changed 🤣
![image](https://user-images.githubusercontent.com/106069445/170259911-a8e4cfec-de76-4c61-9a58-b1839f652686.png)

Do you know if this is a related issue or a different topic?

**Comment by TimRudy** [comment]
Different issue, getting APIO working. The Windows issue was  
![image](https://user-images.githubusercontent.com/3942818/170261461-f31ff5d5-6d00-4ea2-bcb1-05dad5fbc003.png)
or  
![image](https://user-images.githubusercontent.com/3942818/170261569-2be413ce-aecf-426b-afe8-94cfe1e450a4.png)

**Comment by Obijuan** [comment]
These errors are also related to the drivers. Usually they show up when the driver is not installed (the software tries to open the device but it receives an error from the driver). The typicall action is to install the driver

After you get the error, can you click on the View/Command output and send an screenshot? I need to collect more information about it

(I assume that now Zadig worked ok and you already got the ICE40UP5K Breakout (Interface 0) Label)

**Comment by MeindlD** [comment]
Hi Tim and Obijuan,

thanks again for your support. Sorry for the late answer, but I didn't have access tot he hardware the past few days.

So this is my Command Output:
![image](https://user-images.githubusercontent.com/106069445/170927894-92462ccc-5daa-4b48-a33f-a1fdffc232cb.png)

In the device manager, my board is still named "USB <-> Serial Converter". But as I already wrote above: I have no idea, how i could get rid of this driver. Nevertheless the right driver for the board should have been installed, as it is listed as "libusbK USB devices"
![image](https://user-images.githubusercontent.com/106069445/170928293-107ff284-ef55-4757-a64c-caee2f849d8a.png)

**Comment by zambujal** [comment]
don't know if it's the same thing... but I had some problems with the icestick lattice just changed the usb descriptor name... 

The descriptor doesn't correspond (they changed it) so you have to change the boards.json (search for it in the users folder...) to the new usb descriptor for this to work.
[https://blog.j2i.net/2023/01/27/resolving-board-icestick-not-connected-for-the-lattice-icestick-hx1k-with-apio/](url) Apio as the same problem.

**Comment by holography-be** [comment]
Hello,
I have the same problem with my icestick :-(

![image](https://github.com/FPGAwars/icestudio/assets/16881771/683a1df6-3318-4ebe-91bd-a86cced2f267)

Where did you found the boards.json ?
I'm looking on my all disk but not found it.

Thank you.

**Comment by cavearr** [comment]
The last wip (https://downloads.icestudio.io) contains the development toolchain with the latests yosys version that is more compatible with usb in windows (now you don't need zadig).

Try it and if you have problems reopen this.
