### ISSUE TITLE
"Error executting command" at first run

### ISSUE THREAD

**Issue by denizzzka** [FPGAwars/icestudio#633]
Hi! I am newbie

Tried to run both RC and WIP AppImages on clean Debian Linux system, but after selection of any board got this error during `virtualenv` creation:

![image](https://user-images.githubusercontent.com/974632/171880878-1bd0fb56-4810-4acd-9496-c9cb1f92a809.png)

Python 3.10 is installed on my system:
```
denizzz@denpc:~$ ls -l /usr/bin/python3.10
-rwxr-xr-x 1 root root 5896776 May 14 08:40 /usr/bin/python3.10
```

Then, probably, because of this error `virtualenv` creation stalls on 20%

**Comment by cavearr** [comment]
Try installing distutils:

sudo apt install python3-distutils

**Comment by denizzzka** [comment]
> Try installing distutils

Already installed, with `-extras`

Also found in console:
```
/bin/sh: 1: /usr/local/Cellar/python/3.8.2/bin/python3: not found
/bin/sh: 1: /usr/local/Cellar/python/3.7.7/bin/python3: not found
```

**Comment by Obijuan** [comment]
Hi @denizzzka ,

Please, check the instalation instructions on the wiki

https://github.com/FPGAwars/icestudio/wiki/Installation#ubuntu-2004

These instructiins are for Ubuntu, but should also work for Debian

It seems that you have missed to install the python3-venv package

The error message you get is raised because the virtual python env (venv) cannot be executed

**Comment by denizzzka** [comment]
@Obijuan thank you! Yes, I skiped this step. Now it works!

**Comment by darkredhorse** [comment]
Although issue is closed, I thought I would just add a confirmation that the windows installer also had an issue, but I just rand through the manual install steps and it seem s good to go.   Repeated warnings about the platform name "windows_amd64" not matching popped up, but the scripts then attempted "windows" and exited successfully.
