### ISSUE TITLE
Tips about SVG image

### ISSUE THREAD

**Issue by laulin** [FPGAwars/icestudio#635]
Hello :) 

Do you have tips to share about having good component image (icon ?) ? What piece of software to you use to create them easily and fastly ?

**Comment by cavearr** [comment]
Hi Laulin! you can use inkscape , it is open source and multi platform.

https://inkscape.org/es/

**Comment by laulin** [comment]
Indeed, inkscape is an exellent vector drawing tool. But it was not my mind, I was more thinking about stuffs like that : 

- https://suncatcherstudio.com/image-text-editor/ : create a SVG based on a text, good to create fast label for you components
- https://www.flaticon.com/fr/ : find icon in svg 

May be some other users have that kind of tips ? Do you think such links can be added to the wiki ?

**Comment by cavearr** [comment]
Ah! i don't understand you initialiy! i'm look for icons usually at https://www.iconfinder.com/
But there are many open source sites, i'll try to put in this thread or in the wiki.

Thanks!

**Comment by cavearr** [comment]
For the moment , i'm closing this thread, is you need clarify something reopen it.
