### ISSUE TITLE
stopNW: NWJS_STOP fails on Windows

### ISSUE THREAD

**Issue by omardiaa** [FPGAwars/icestudio#644]
When I try to start using `npm run start` or `grunt serve`, the NWJS_STOP task fails.

**Comment by omardiaa** [comment]
I debugged this issue for a while and I discovered that it was caused by using gitbash not a command line. The problem was that the `NWJS_WIN_STOP` command was: "taskkill /F /IM nw.exe >NUL 2>&1". 

Git bash does not understand /F. So, the solution to this issue was using "//" rather than "/": 
`const NWJS_WIN_STOP = "taskkill //F //IM nw.exe >NUL 2>&1";`

**Comment by cavearr** [comment]
Thanks @omardiaa !
