### ISSUE TITLE
Build Info disappears immediatly

### ISSUE THREAD

**Issue by BPJWES** [FPGAwars/icestudio#647]
When building the project there used to be a summary of the build results displayed below.
![afbeelding](https://user-images.githubusercontent.com/13208934/182127037-75545cba-d89a-46ff-b4bf-9aed86526bb7.png)

Using the newest WIP on windows 11, the build notification disappears within approximately .5 sec, and the build summary does not appear at all anymore.

This does not seem to be a problem when using windows 8.1
This is the version i am running:

![afbeelding](https://user-images.githubusercontent.com/13208934/182127445-c8bb2d43-1ec9-4d10-81fb-6637319fd9c9.png)

I am running Window 11 Home version 21H2

The build does however seem to be completing correctly

**Comment by jojo535275** [comment]
hello BPJWES,

I just installed the very last version (same as you have), on my win10 and no problem !

Do you still have a tick next to Fpga ressources (in the view menu) ?


![fpga ressources tic](https://user-images.githubusercontent.com/65027759/182192901-05d1c8b8-76a4-486a-ab09-f0c63dc3f275.JPG)

Maybe, for some unknown reasons, it is being dis-activated during the build process ,on  your win 11 machine !?...
