### ISSUE TITLE
alchitry cu 

### ISSUE THREAD

**Issue by juanmicro** [FPGAwars/icestudio#648]
icestudio tiene un error en el  Pinout  tx el numero de pin corresponde al  de rx  ;

**Comment by cavearr** [comment]
Podrías indicarme los números de pin para el tx y el rx?

No tengo esta tarjeta y no puedo validarlo, si pudieras indicármelo, realizo los cambios genero una nueva wip y si pudieras probarla te lo agradecería.

Gracias!

**Comment by juanmicro** [comment]
hola yo lo modifique asi y funciona perfectamente
# ------------ FTDI 1 ---------------------------------------------------------
# UART
set_io --warn-no-port TX  M9  # output
set_io --warn-no-port RX  P14  # input


gracias por el programa que habéis creado estoy muy agradecido.

**Comment by juanmicro** [comment]
hola yo lo modifique asi y funciona perfectamente
# ------------ FTDI 1 ---------------------------------------------------------
# UART
set_io --warn-no-port TX  M9  # output
set_io --warn-no-port RX  P14  # input

gracias por el programa que habéis creado estoy muy agradecido.


De: Carlos Venegas ***@***.***>
Enviado el: ‎miércoles‎, ‎17‎ de ‎agosto‎ de ‎2022 ‎23‎:‎02
Para: ***@***.***>
CC: c ***@***.***>, ***@***.***>


Podrías indicarme los números de pin para el tx y el rx?

No tengo esta tarjeta y no puedo validarlo, si pudieras indicármelo, realizo los cambios genero una nueva wip y si pudieras probarla te lo agradecería.

Gracias!

**Comment by cavearr** [comment]
Sorry for the long delay, your changes has been applied and are available in the next hours in the latest wips . 

You can update from github actions actifacts or easily from https://downloads.icestudio.io
