### ISSUE TITLE
ICEFun board, LEDs no reaction

### ISSUE THREAD

**Issue by FPGA7** [FPGAwars/icestudio#650]
I worked with TinyFPGA BX, all ok. 
Then I changed to ICEFun board. 
![Model](https://user-images.githubusercontent.com/112242064/187021245-5d20a2c3-9b46-47ad-93d5-19e8268276ac.jpg)
Form me there's no way on switching the selected LED on. But when choosing speaker as output I can hear the prescaled clock signal as wanted. Is there any special point to respect with LEDs on this board?
For the output LED0 can't be the choice.

**Comment by cavearr** [comment]
I think this is a problem for the pcf file. This is the description of the board.
I don't have the icefun board, if i'll try some changes could you help me in the debugging process?

Thanks!

**Comment by FPGA7** [comment]
Thank you for your help offer. I will help you in the debugging process.

**Comment by FPGA7** [comment]
I've got it, a very simple mistake. ICEfun has an array og LEDs. Each LED is defined by line and number. So you have to declare in addition the line.
![leds](https://user-images.githubusercontent.com/112242064/187075478-2b8b6a69-4d93-45d7-b199-aca95a39349c.jpg)
.

**Comment by cavearr** [comment]
Thanks for the feedback! i'm buying an ICEFun for future problems.

Thanks again!
