### ISSUE TITLE
upduino v3.1 SPI

### ISSUE THREAD

**Issue by tlerner-pizza** [FPGAwars/icestudio#654]
Hi I am looking to use SPI for the upduino v3.1 but in the input/output blocks I don't see any dropdown for anything other than the GPIO pins (and LEDs on output blocks) so I cannot select IO as MISO, MOSI, SCLK, and SS. is this functionality available or can it be added? Thanks

Edit: For context, I want to use the Jedi collection to get the SPI blocks: https://github.com/FPGAwars/Collection-Jedi

**Comment by cavearr** [comment]
Try to explain your problem at https://groups.google.com/g/fpga-wars-explorando-el-lado-libre. this starts as spanish community but now people reply en english as well. That is the best place for this specific problem about boards integrations or blocks.

for the moment close this issue, reopen if it is necesary.
