### ISSUE TITLE
Icestudio 0.10-rc1 Botones Basico-Bit-Logica-Setup no aparecen

### ISSUE THREAD

**Issue by Fito74** [FPGAwars/icestudio#664]
Buenas noches desde Argentina.
Es la primera vez que instalo Icestudio, y desde el vamos no aparecen los botones que menciono en el asunto.
Ya sea que se carga la colección por default, o la colección Academia-Jedi-HW-05 dichos botones no aparecen.

Estoy usando Debian 11 (Bullseye) y Gnome 3.38.5

Gracias y saludos cordiales!

Fito

**Comment by Obijuan** [comment]
A partir de icestudio 0.9 la interfaz ha cambiado. Una vez instaladas las colecciones, tienes que abrir este panel y ahí encontrarás todos los componentes

![](https://github.com/myTeachingURJC/Mecatronica/raw/main/wiki/L06/Reto-01-Ledon-03.gif) 

Te dejo estos dos enlaces de la documentación que uso con mis estudiantes en la asignatura de Mecatrónica. Les enseño a hacer circuitos digitales con Icestudio:

* https://github.com/myTeachingURJC/Mecatronica/wiki/L5:-Dise%C3%B1o-digital.-FPGAs-Libres.-Icestudio

* https://github.com/myTeachingURJC/Mecatronica/wiki/L6:-Dise%C3%B1o-digital-(II):-Domadores-de-bits
