### ISSUE TITLE
Toolchain installation issues

### ISSUE THREAD

**Issue by muxia1954** [FPGAwars/icestudio#675]
The used PC was broken
Install a new PC(windows 11) for icestudio
 However,the tool chain cannot be installed with the error.
Can't use it in windows11?

An error occurs, generates a Create virtualenv...20%, 
and does not continue from

--- Error message below ---
error executting command pyton.exe,m
venv,"C:\user\admin\icestudio\venv"

help me

**Comment by cavearr** [comment]
What python version have you installed?

**Comment by muxia1954** [comment]
Ver.3.9 in the installation package.

**Comment by muxia1954** [comment]
I installed the toolchain again this morning
Installation without error

Thank you very much、Muchas gracias 
ありがとう。

**Comment by cavearr** [comment]
Download the last wip at https://icestudio.io. i think this issue is solved. If you try it and works, plase tell us in this thread.

**Comment by cavearr** [comment]
For the moment i close this issue, if problem persists open it again.
