### ISSUE TITLE
RFE: Please provide the minimum HW (space) requirements

### ISSUE THREAD

**Issue by efa** [FPGAwars/icestudio#676]
in donwloaded the 200 MB AppImage on a Debian 11, I put that in /opt/ICEstudio, and made executable.
Once selected the Board, I downloaded the toolchain, it put that in /home, filling my users partition, with about 1 GB.

1) can you please supply the minimum required space (I know ISE and Vivado are massive, but declared)
2) is there a toolchain installation procedure to put that in /opt (or near ICEstudio appImage)
3) the list of supported FPGA board is quite impressive inside the menu selection, but on web site seems limited to AlhambraII, please complete the web page
![ICEstudio_FPGAboard0](https://user-images.githubusercontent.com/1578980/218316973-b2395448-75fb-446d-bf1c-ca18d0bd1833.png)
![ICEstudio_FPGAboard1](https://user-images.githubusercontent.com/1578980/218316979-ca8d2a26-c536-4e2c-828e-26076dee408a.png)

**Comment by cavearr** [comment]
Hello @efa! 

1) We are working to minimize the size of Icestudio but at the moment you need around 1.5GB free, if you reserve 2GB it's better and you won't have any problem.
In this 2GB I am counting the icestudio app, toolchain and virtual environments created by python, but you must have python installed on your OS (probably around 500MB-1G if you don't have it installed).

2) Very soon you could define the settings directory (.icestudio directory in your home directory) but for the moment you coud make a link with "ln" command, for example:

_ln -s /home/your_user_home_directory/.icestudio /opt/icestudio_home_ 

3) We are working on a new website, with a new look, updated information and new things, but we are going step by step and it will probably take a few months to get everything online, but we are on our way. .

Thank you very much for using Icestudio and reporting any type of comment or collaboration, and if you have more questions, you can reopen this topic, open a new one or go to the fpgawars group, this group starts as a Spanish group but right now there are people from some countries and conversations evolve in English.
