### ISSUE TITLE
Upduino 3.1 No Basic > Input Menus after toolchain install

### ISSUE THREAD

**Issue by mccoyg** [FPGAwars/icestudio#677]
I am on a Mac and these menus are missing after board selection and stable toolchain install.

<img width="897" alt="Screen Shot 2023-02-15 at 14 13 23" src="https://user-images.githubusercontent.com/14010752/219189047-9063d3db-70ea-4238-8a19-ee189d36dd59.png">

all menus missing even though successfully installed toolchain.

**Comment by mccoyg** [comment]
Its supposed to look like this:
<img width="492" alt="Screen Shot 2023-02-15 at 14 29 20" src="https://user-images.githubusercontent.com/14010752/219200265-53c72a68-79fd-4a3b-b5c3-95819a7df84d.png">

**Comment by jojo535275** [comment]
Hello
This is normal, to simplify the logic, about 1 year ago, we converted the Basic menu to a floating "toolbox" removing it from the toolbar.
To access to this toolbox, you have two options :
- go to menu Edit / toolbox
- Just hit Ctrl +T on your keyboard (or corresponding keys for mac)
For the remaining menus that you mentioned, they were made to pick-up blocks in a selected collection. 
Now you have to use the collection manager to pick up all your blocks in the collections ( previously loaded in your icestudio).

**Comment by Obijuan** [comment]
In this animation you can see the new approach:
![Peek 2023-02-16 08-48](https://user-images.githubusercontent.com/1286062/219301481-e23d2267-549e-4a17-8923-f62781341105.gif)

Inside the toolbox you will see the default collection and all the collections that you have installed manually

**Comment by mccoyg** [comment]
All ok, thank you for your quick response to the newb!
