### ISSUE TITLE
Icestudio has problems with Python 3.11.2

### ISSUE THREAD

**Issue by HttpRafa** [FPGAwars/icestudio#682]
I think IceStudio doesn't understand Python version 3.11.2. 
Because I get an error during the toolchain installation that at least 3.7 must be installed.

![Screenshot_2](https://user-images.githubusercontent.com/60099368/221419809-3cf547ab-8d59-483f-b9c9-a0267deea369.png)
![Screenshot_3](https://user-images.githubusercontent.com/60099368/221419811-40c1a1ec-d1e7-41e6-9f92-041cc2ba18ab.png)

**Comment by gfcwfzkm** [comment]
Just installed the program myself and I get the exactly same error. Got python 3.11 installed as well.

**Comment by cavearr** [comment]
What operating system are you using?

**Comment by HttpRafa** [comment]
At this time i was using Windows 11

**Comment by bruno504luis** [comment]
Any advice by now? I've got win8.1 and same problem.

**Comment by bruno504luis** [comment]
> 

Ok, I used vers 3.10.11 it worked.

**Comment by Chandler-Kluser** [comment]
I am using Endeavour OS and I have had the same issue in installation:

![image](https://github.com/FPGAwars/icestudio/assets/29960960/6c7d37b9-ddd6-4e29-8e7c-e604cc8acc4e)

![image](https://github.com/FPGAwars/icestudio/assets/29960960/f521607d-f355-46ec-af4f-4192d5bfa1d6)

I believe there is an issue with python 3.11

**Comment by cavearr** [comment]
Hi @Chandler-Kluser !, could you execute :

- which python
- which python3
- python --version
- python3 --version

**Comment by Chandler-Kluser** [comment]
> Hi @Chandler-Kluser !, could you execute :
> 
>     * which python
> 
>     * which python3
> 
>     * python --version
> 
>     * python3 --version

![image](https://github.com/FPGAwars/icestudio/assets/29960960/3242f92c-c9d9-43d9-adbd-e126a539a01b)

**Comment by cavearr** [comment]
Hi! could you install the last WIP version from https://downloads.icestudio.io and try if it works on your environment?

**Comment by GhostDog98** [comment]
> Hi! could you install the last WIP version from https://downloads.icestudio.io and try if it works on your environment?

@cavearr I've been having this same issue with the same results for `which python`, this fixed the issue, perfect timing as I installed icestudio not 5 minutes ago :laughing:

**Comment by cavearr** [comment]
Thanks!!! if is it necessary reopen the issue! :)

**Comment by Chandler-Kluser** [comment]
It worked!!! Thanks a lot!!!
