### ISSUE TITLE
Mac Toolbar Missing Items

### ISSUE THREAD

**Issue by dan-sherwin** [FPGAwars/icestudio#691]
I just got Icestudio installed on my Mac.  Im using an Alchitry Cu iCE40-HX8K board.  I did a successful install of app and toolchain.  I am able to load any of the example projects, build it, upload it to the board, and it works as expected.  

The problem is, the IDE toolbar has none of the basic items I expected to see like the dropdowns like Bit, Logic, and Setup.  The only things I have is File, Edit, View, Select, Tools, Basic, and Help.  Im attaching a screen shot.  

<img width="1012" alt="Screenshot 2023-07-10 at 3 43 44 AM" src="https://github.com/FPGAwars/icestudio/assets/113303204/4a44a273-93ee-44e7-af8c-c06db92a3ec1">

**Comment by Obijuan** [comment]
Please, have a look at issue #677

The Icestudio blocks are available inside the new toolbox window

**Comment by dan-sherwin** [comment]
I looked for duplicate issues, I swear, but I missed finding that one.  Thank you and sorry for the dup issue.

**Comment by Obijuan** [comment]
Hey! No problem 😀️ . It is usually difficult to find similar issues because Icestudio is still in development and it is constantly changing...
