### ISSUE TITLE
Can't install toolchain on Linux Mint.

### ISSUE THREAD

**Issue by multivactubes** [FPGAwars/icestudio#692]
![image](https://github.com/FPGAwars/icestudio/assets/99918640/ba644537-cbb8-4913-8a3a-31c98502d4e6)

I'm getting these errors when I try to install the toolchain. I'm on Linux Mint 21.1 (Vera). I have python 3.10.6 installed along with pip 22.0.2.

Any ideas?

**Comment by nitrousnrg** [comment]
Same problem in kubuntu. Neither stable or WIP can install the toolchain

**Comment by nitrousnrg** [comment]
Solved in stable by installing:
sudo apt install python3-venv

**Comment by Obijuan** [comment]
Yes, it is mention in the documentation, in the Installation section:

https://github.com/FPGAwars/icestudio/wiki/Installation#introduction

But maybe it would be a good idea to let Icestudio check that the python venv module is installed

**Comment by Obijuan** [comment]
I will wait for @multivactubes to test it before closing the issue
