### ISSUE TITLE
Icestudio wants to install Python 3.9.9 while I already have Python 3.11.3 installed. 

### ISSUE THREAD

**Issue by wgaylord** [FPGAwars/icestudio#694]
I am trying to install the Windows 64-bit version of icestudio on Windows 10. (Version 0.10 according to the file) And the install insists on installing Python 3.9.9. 

I have tried the nightly / WIP build `0.10.1w202306300406` which is the newest one and it to wants to install Python 3.9.9 for some reason. 

Running `where python` turns the following on my system. 

```
C:\Users\chibill>where python
C:\Python311\python.exe
C:\Users\chibill\AppData\Local\Microsoft\WindowsApps\python.exe
```
Where the weird path in AppData is Microsoft's stupid thing to try and make you install python thru the appstore is its not installed on your system. 

Any solutions would be greatly appreciated.

**Comment by cavearr** [comment]
Hi! i'm checking it and updating window installer, tell you soon.

**Comment by wgaylord** [comment]
Any information? Just tried the nightly / WIP build `0.10.1w202307290607` and no change.

**Comment by cavearr** [comment]
Hi! i'm working in a new installer, should be ready along tihs week, but if you can't wait, for the moment you could download de zip version, from https://downloads.icestudio.io/  decompress an execute icestudio directly.


<img width="1596" alt="Captura de pantalla 2023-08-15 a las 23 28 41" src="https://github.com/FPGAwars/icestudio/assets/6904865/a3be0a4c-cbc5-41a7-9253-83641f8be0a7">

**Comment by cavearr** [comment]
the last wip works with python 12 , when you try to install icestudio, the python installer detetcts your previous python and ask you for install or not, donwload an try it if you have any problem reopen this.

Thanks!

**Comment by wgaylord** [comment]
Having a similar issue again where I have python 3.13 installed and it wants to install 3.12.  Tried to use the nightly builds but none of them will download only returning a json response.

**Comment by cavearr** [comment]
Hi william! i'm reworking some things,soon works again, sorry for the inconvenience.

**Comment by cavearr** [comment]
Current stable version is outdate, we are in process now to release the new one (current branch) if you want to try it download from https://downloads.icestudio.io

I'm closing this issue because is outdated and we need to reduce noise for real bugs in the new pre-release, if you needed reopen it.
