### ISSUE TITLE
icestudio runs pushbutton example for OK-iCE40Pro failed on MacOS

### ISSUE THREAD

**Issue by nandemoi** [FPGAwars/icestudio#696]
Example:
Basic → 06. Pushbutton and LED.ice

Error Message:
yosys -p "synth_ice40 -json hardware.json" -q main.v
nextpnr-ice40 --up5k --package sg48 --json hardware.json --asc hardware.asc --pcf main.pcf -q
scons: *** [hardware.asc] Error -11

OS:
Ventura 13.4 (intel Core i3)
failed too on Ventura 13.4.1 (Apple M1)

By the way the flattened MacOSaarch64 (ARM64) didn't seem to contain an execution file for MacOS.

Thank you.

**Comment by cavearr** [comment]
hi! Do you install apio toolchain? click on "install development version"

<img width="992" alt="Captura de pantalla 2023-08-20 a las 15 58 58" src="https://github.com/FPGAwars/icestudio/assets/6904865/c7623c0a-38c6-4d4e-852e-ca92396c2b33">

And if it is possible, install the latest wip from https://downloads.icestudio.io

**Comment by nandemoi** [comment]
Yes, I did. The LED only examples load fine.

**Comment by cavearr** [comment]
How we don't have notices about it, I'm closing the issue, if you try the possible solution commented or have any other comment, reopen.

Thanks!
