### ISSUE TITLE
wips are actualy not downloadable

### ISSUE THREAD

**Issue by jojo535275** [FPGAwars/icestudio#697]
Hello guys, 
The wip versions of icestudio are actually not downloadable from the icestudio website!
Probably due to the fact that they are "expired artifacts" in GitHub actions ?!

![Capturegit](https://github.com/FPGAwars/icestudio/assets/65027759/9f61ce1f-2a37-48db-8c8e-2d0d6f5983bb)

**Comment by cavearr** [comment]
Thanks Jo!! now i'm generate new one!

**Comment by cavearr** [comment]
Fixed!!

**Comment by jojo535275** [comment]
yes, i just could download it,
Gracias Charli
