### ISSUE TITLE
Unable to connect input to pull-up-inv configuration block.

### ISSUE THREAD

**Issue by C47D** [FPGAwars/icestudio#70]
Hi,
I'm unable to connect a input block to the input terminal of a pull-up-inv configuration block. This is happening having the latest code from the repository.
Any chances i'm doing something wrong?
Find the test project attached.

[test1.ice.zip](https://github.com/FPGAwars/icestudio/files/428743/test1.ice.zip)

**Comment by Jesus89** [comment]
Closed in 2e59cca782ce585600106bb8447108a4b86bcb58.

Thanks for the feedback.
