### ISSUE TITLE
https://icestudio.io/ is down

### ISSUE THREAD

**Issue by cadr** [FPGAwars/icestudio#711]
The github page refers to https://icestudio.io/ (which is also the first search result when looking for this tool).  That site is currently down.  Is it still used?  Should references to it be removed from the github repo?  Thanks!

**Comment by cavearr** [comment]
Hello! Sorry for the inconvenience, I'm updating the site and since yesterday we have had problems with hosting. In the next few hours the site should be active again.

**Comment by cadr** [comment]
Awesome!  Thanks!
