### ISSUE TITLE
noob questions IceFun HX8K led matrix board 

### ISSUE THREAD

**Issue by jmio23** [FPGAwars/icestudio#713]
I got an IceFun HX8K, the one with the LED matrix on it, but I can't figure out which board I need to choose in IceStudio to get started? Had issues building the IceFun examples (gave errors when hitting build, but also the program converted the examples for IceFun, which probably complicates matters for me..)
 

Perhaps there is a better board for me to get started with? The IceFun examples i tried wouldn't build, and I'm too much of an FPGA noob to even know where to start figuring out why or what difference there might be for my specific board...

Also how do I know if the board is actually connected to IceStudio? can't see any visual indication, although windows detected/installed and connects fine apparently

**Comment by jojo535275** [comment]
Hello jmio,

i do not have this board, but, Normaly, for the icefun board (HX8K), you have to select:
![image](https://github.com/FPGAwars/icestudio/assets/65027759/9246b6fa-82d6-460a-bb18-010f15c711b4)

Also have  you installed the "Apio" toolchain? :
![image](https://github.com/FPGAwars/icestudio/assets/65027759/6926834f-4d64-49ff-a140-09d3c445d9ea)

The easiest way to know if you card is well connected, is to try loading a simple blinking led design on your board.
![image](https://github.com/FPGAwars/icestudio/assets/65027759/81334255-6b8d-4f86-a010-d3f46cff80e9)
 - you should accept the alhambra to icefun conversion of the design (in the pop-up window)
 -  and then you have to choose the led you want to blink (in the drop-down menu of the output port(in blue on the above picture  )

**Comment by cavearr** [comment]
I'm closing this issue because i think is solved.

If problem persist of you need to continue it, reopen!

Thanks!
