### ISSUE TITLE
IceStudio stuck on windows 10

### ISSUE THREAD

**Issue by amin-mm-dev** [FPGAwars/icestudio#724]
I got the latest Icestudio release for Windows, but I can't get it to run after installing. It just keeps loading indefinitely, even after trying different versions and turning off AVG and Windows Defender.

I also granted administrator rights.

<img width="717" alt="image" src="https://github.com/FPGAwars/icestudio/assets/40408675/e1532e9d-a224-4821-afb1-768dbbf1c145">

**Comment by cavearr** [comment]
What version are you installing? Try the first in the table for your operating system at https://downloads.icestudio.io/

**Comment by amin-mm-dev** [comment]
<img width="931" alt="image" src="https://github.com/FPGAwars/icestudio/assets/40408675/60bbf1be-5c1c-48ef-9308-7f5104b4086e">

**Comment by amin-mm-dev** [comment]
I installed that version in the previous screenshot

**Comment by cavearr** [comment]
Please check the latest wip, your problem could be fix. If the problem persists , plase reopen the issue.
