### ISSUE TITLE
FPGA resources used or LUTs remaining

### ISSUE THREAD

**Issue by ssjimh** [FPGAwars/icestudio#727]
Does icestation tell us the FPGA resources used for a build, or the LUTs remaining in the chip?

**Comment by cavearr** [comment]
yes , you could view in the console output after you build your project:

<img width="267" alt="Captura de pantalla 2024-03-18 a las 18 24 42" src="https://github.com/FPGAwars/icestudio/assets/6904865/0db1f298-4c00-4601-8a62-59b1715e76d7">
