### ISSUE TITLE
When inside a block (Read only), a component can be dragged in from Collection Manager

### ISSUE THREAD

**Issue by TimRudy** [FPGAwars/icestudio#731]
The action of selecting or dragging from Collection Manager should be blocked in Read only case.

If not, the new block can actually "replace" something and wire itself into the Read only design. Which is funny because you can't delete it and you can't edit the wires.

A simple problem. I will create a PR at some point.

**Comment by cavearr** [comment]
Fixed in the latest wips, i'm closing it if is needed reopen it!
