### ISSUE TITLE
v0.11 Linux installation missing menu options

### ISSUE THREAD

**Issue by bgalport** [FPGAwars/icestudio#740]
Just installed the latest version (0.11) on Ubuntu 24.04 and find that the only the Basic menu option is displayed. The Bit, Logic and other options I see on web examples are missing. I've tried loading other collections but nothing changes. I am able to load all the example files. Have I missed something?

<img width="1283" alt="image" src="https://github.com/FPGAwars/icestudio/assets/3055198/b10734d4-c188-4b55-b83f-0321190cc096">

**Comment by bgalport** [comment]
Hi @cavearr, I used the Tools->Collections->Add option to add Collection-Jedi. Even the default collection should have included logic blocks shouldn't it?

**Comment by bgalport** [comment]
Thank you! I would never have thought of looking there. I can now see all the available blocks. 

<img width="1286" alt="image" src="https://github.com/FPGAwars/icestudio/assets/3055198/cd24cb9c-7cf4-4cf8-b50b-882d2c4e0d96">

**Comment by cavearr** [comment]
You are welcome!

**Comment by danielzgtg** [comment]
@cavearr Can you update the pictures at https://icestudio.readthedocs.io/en/latest/source/howto.html please?

**Comment by cavearr** [comment]
Hi Daniel, this documentation is very outdated and should be removed soon. The new version of IceStudio will be available soon and will have many changes and good documentation. We apologize for the inconvenience.
