### ISSUE TITLE
Program close with ceartain combinations. 

### ISSUE THREAD

**Issue by BernonR** [FPGAwars/icestudio#773]
After several tries, I found that when I insert in the board. 2 ANDs + 2 NORs the program will close automatically. here is a GIFT

![Desktop 2024 10 14 - 10 36 42 01](https://github.com/user-attachments/assets/0672ec17-9969-413b-9ab9-00a72fefe555)

**Comment by cavearr** [comment]
Thanks @BernonR  ! what version are you using?

**Comment by BernonR** [comment]
version 5, is the only one I found with fewer errors than others.  I'm using a FPGA an it works perfectly with that version.

**Comment by cavearr** [comment]
Please, attach an screenshot of this menu panel opened:

<img width="350" alt="Captura de pantalla 2024-10-14 a las 20 54 54" src="https://github.com/user-attachments/assets/4a96dc4d-5930-40e3-a747-fd35662d1ecd">

**Comment by cavearr** [comment]
Hi your gif is very small but i think this is other tool or non oficial fork.

If i'm wrong please reopen the issue and attach better image or video with more resolution.

Thanks!
