### ISSUE TITLE
Readme progress bar broken

### ISSUE THREAD

**Issue by cavearr** [FPGAwars/icestudio#776]
The service https://progress-bar.dev  is broken almost today.

I'm opening this issue to remember check it in the next days and is this not work look for alternative.

**Comment by lmcapacho** [comment]
The domain https://progress-bar.dev has expired. A fork has been created at https://github.com/guibranco/progressbar, which can be used with the domain https://progress-bar.xyz

**Comment by cavearr** [comment]
Thanks a lot! i don't research around this, thanks for your tip!
