### ISSUE TITLE
apio.ini for ECP5

### ISSUE THREAD

**Issue by tconsult** [FPGAwars/icestudio#777]
Info:['-b''--board'] is deprecated, 
Info:['-t',--top-module'] isdeprcated. Info; Project has no apio.ini File

**Comment by cavearr** [comment]
hi @tconsult ! what version of icestudio and apio are you using?

**Comment by tconsult** [comment]
Hi cavearr  , i use Icestudio-012-win64.exe
and i could not find the apio.ini File

**Comment by cavearr** [comment]
Please could you attach an screenshot of this panel menu :

![Uploading Captura de pantalla 2024-11-03 a las 0.15.26.png…]()

**Comment by cavearr** [comment]
Please could you attach an screenshot of this panel menu :

<img width="461" alt="Captura de pantalla 2024-11-03 a las 0 15 26" src="https://github.com/user-attachments/assets/332fa790-1c95-4e15-aa65-e1a623e3b536">

**Comment by tconsult** [comment]
Enclosed is a PDF File with the screenshots.

 

Thank you for your support

 

Von: Carlos Venegas Arrabé ***@***.***> 
Gesendet: Sonntag, 3. November 2024 00:18
An: FPGAwars/icestudio ***@***.***>
Cc: tconsult ***@***.***>; Mention ***@***.***>
Betreff: Re: [FPGAwars/icestudio] apio.ini for ECP5 (Issue #777)

 

Please could you attach an screenshot of this panel menu :

Captura.de.pantalla.2024-11-03.a.las.0.15.26.png (view on web) <https://github.com/user-attachments/assets/332fa790-1c95-4e15-aa65-e1a623e3b536>

**Comment by cavearr** [comment]
Hi @tconsult ! i can't view any pdf!

**Comment by tconsult** [comment]
Sorry , here as *.png Files

 

Von: Carlos Venegas Arrabé ***@***.***> 
Gesendet: Sonntag, 3. November 2024 14:52
An: FPGAwars/icestudio ***@***.***>
Cc: tconsult ***@***.***>; Mention ***@***.***>
Betreff: Re: [FPGAwars/icestudio] apio.ini for ECP5 (Issue #777)

 

Hi @tconsult <https://github.com/tconsult>  ! i can't view any pdf!

**Comment by cavearr** [comment]
sorry @tconsult but i can't view your screenshot!

**Comment by Xorlent** [comment]
@tconsult I suspect you have not completed the Toolchain setup.

1. Unplug your ECP5 from USB
2. Open Tools -> Toolchain -> Update (Latest stable)
3. After the update, click the popup dialog in the lower-right corner of the program window ("Click here to setup the drivers")
4. Reconnect your ECP5 board
5. Wait a few moments
6. Click "OK" and replace the ECP5 Development Board (Interface 0) entry with the libusbK driver
7. Once the install is done, you can close the window and unplug your board.
8. Reconnect your board and now upload your project

I hope this helps.

**Comment by cavearr** [comment]
Hi! from the last wips https://downloads.icestudio.io (0.13.1w202412210312) and newer, install apio develpment from toolchain menu and all works now.

I'm closing the issue, reopen if needed.
