### ISSUE TITLE
Caja de código + scroll

### ISSUE THREAD

**Issue by Democrito** [FPGAwars/icestudio#778]
Cuando se abre un circuito y hay una caja de código, sólo sale la primera línea, el resto no aparece hasta cambiar el zoom o cuando se maximiza a pantalla completa, la cosa es que cuando la ventana cambia es cuando aparece el código correctamente, con su scroll y todo eso. 

Según he visto, al menos ahora (al tratar de comprobar lo que estoy diciendo) sólo sucede si la caja de código está en el top, al navegar en módulos siempre sale bien o eso me ha parecido.

**Comment by cavearr** [comment]
Desde esta wip debería estar resuelto: 0.12.2w202411100611

**Comment by Democrito** [comment]
En mi Windows sigue dando guerra ese tema. Probada la versión terminada en 611

**Comment by Democrito** [comment]
Vale, con esta nueva wip ya se ha resuelto. Gracias!
