### ISSUE TITLE
Se solapan líneas de conexiones

### ISSUE THREAD

**Issue by Democrito** [FPGAwars/icestudio#780]
Cuando abres cualquier circuito, incluido módulos, hay líneas (conexiones) que no terminan de estar bien. Pero al mover cualquier entrada o salida o cualquier movimiento de componentes, todo se pone bien, tal como el diseñador lo hizo. Más que nada es que a veces se puede confundir conexiones porque puede llegar a solaparse algunas líneas, especialmente en circuitos de mediana-alta complejidad. Lo he comprobado en el top, pero no sé si esto sucede en módulos, que creo que sí, al menos en el pasado.

![solapamiento de lineas](https://github.com/user-attachments/assets/aad0df95-cd95-4a52-bf7c-7fbb461e6ad5)

**Comment by cavearr** [comment]
¿me puedes pasar ese diseño? par intenar reproducirlo?
