### ISSUE TITLE
IO "naranjas" en "guardar cómo"

### ISSUE THREAD

**Issue by Democrito** [FPGAwars/icestudio#783]
Cuando queremos **guardar un módulo como circuito aparte**(al darle a "Guardar como."), al abrirlo ese circuito que fue guardado, muchas veces salen las cajas de entrada/salida con un formato que no permite hacer cambios (convertirlo como IO físico o de módulo). Salen como cajas de entrada/salida plano de color naranja. Al intentar cambiar sus propiedades no surte efecto y no hay más remedio que eliminarlas para poder ser sustituidas por IO nuevas, y con ello se pierden las conexiones que tenía.

![IO naranjas](https://github.com/user-attachments/assets/6e9a95ad-c1f0-4f00-a0a4-2007d2ea0097)

**Comment by cavearr** [comment]
Solucionado en última wip, cuando puedas comprobarlo , si todo está bien cierra la issue 👍

**Comment by Democrito** [comment]
Ya trabaja perfectamente esta parte y se guarda tal como se ve antes de guardar.
