### ISSUE TITLE
Doble clic en módulos con zoom al máximo

### ISSUE THREAD

**Issue by Democrito** [FPGAwars/icestudio#784]
Cuando el zoom es máximo y quieres ver el interior de un módulo, no se abre. Hay que alejarse con el zoom para que el doble clic tenga efecto.

![doble clic con zoom maximo](https://github.com/user-attachments/assets/332e3c89-1e0b-4900-9d4e-3081b4e910c2)

**Comment by cavearr** [comment]
Resuelto en la última wip, cuando checkes cierra la issue.

Gracias!

**Comment by jojo535275** [comment]
Little remark: i am still on version 0.11.3W202406110606
and this problem was already present on that version!

i will later update my icestudio version and check again!
Thanks Charli and Democrito for loocking at all this little but important problems!

**Comment by cavearr** [comment]
Hi @jojo535275 !! in the last wip 0.12.2w202411090811 should be fixed.

I'm organizing with Democrito for a "bug haunting", i'll try to fix the next days ui bugs that are rounding for a long time and are anoying with the objetive of have a robust wip version.

If you have detected bugs please create issues  to have it in the radar.

**Comment by Democrito** [comment]
Reparado y funcionando bien en la última wip.
