### ISSUE TITLE
edit a code block input, output and parameter after already made one

### ISSUE THREAD

**Issue by hasan12977** [FPGAwars/icestudio#786]
hi, I made this code block but i wanted to move those parameters outside of the block like prescalerN module after I already created this code block. i was wondering if there is a way to change its inputs and outputs and parameters afterward, if not, is it possible to integrate that feature in future release?

![Screenshot 2024-11-15 at 11 42 11 AM](https://github.com/user-attachments/assets/300de16e-8fd9-4e9d-8469-2884c5af611d)

**Comment by hasan12977** [comment]
i found it. I had to double click on the edge of the block.

**Comment by cavearr** [comment]
Great! if you have any problem tell us!
